### ISSUE TITLE
radar 1

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#176]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/164)

**Comment by whit537** [comment]
Here's what's on my radar this week, and why:

- [ ] Support @chrisdev @citruspi as they get ready for **PyCon** (#111, #160, https://github.com/gratipay/gratipay.com/pull/3301, https://github.com/gratipay/gratipay.com/issues/3221). External pressure because PyCon starts this week!

- [ ] Get export UI out there (https://github.com/gratipay/gratipay.com/issues/3255). This would be an easy thing to land and an easy blog post to write. External pressure because US tax season is almost over. We haven't made a blog post in 7 weeks. We should make a blog post at least once every month.

- [ ] Formulate a plan for migrating away from **Balanced** (https://github.com/gratipay/gratipay.com/issues/67). External pressure because they're going out of business in [73 days](https://daycalc.appspot.com/06/11/2015) and migrating is risky and a lot of work.

- [ ] Tweak our **work process** (https://github.com/gratipay/inside.gratipay.com/issues/163). We almost landed this last week but then the pk id/username issue surfaced so there's still a bit more work to do here. Internal pressure because I'm torqued and embarrassed about Gratipay right now and I can't make it something I'm proud of all by myself. I need you. :-)

- [ ] Work down our [security queue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+label%3ASecurity). I want to get down to **Security 0** and then write a blog post about it. "Security is important to us. We run at Security 0." Internal pressure because running at Security 0 to me is like cleaning the toilet or brushing my teeth or compiling with no warnings. It's just the right way to operate. I've seen some open-source projects with a *lot* of open security issues. It's a case of queue collapse (you're overwhelmed, you're never gonna dig out). I don't want to ever reach that point. Let's get to Security 0 while we still stand a chance, so we can stay there and be good citizens.

- [ ] Organize the **redesign** (https://github.com/gratipay/gratipay.com/issues/3248). This is a big project. https://github.com/gratipay/gratipay.com/issues/3220 and the new [Product](http://inside.gratipay.com/big-picture/product) page were prerequisites. 3220 kicked out a number of issues, next step is to start organizing the work here. Internal pressure because I'm torqued and embarrassed about our product and I see this as the project that's going to turn it into something I'm proud of.

- [ ] Solidify marketing plan (https://github.com/gratipay/inside.gratipay.com/issues/177). Internal pressure because I want more people to be using Gratipay.

- [ ] Deal with **https://github.com/gratipay/postgres.py/pull/43**. External pressure because @Changaco wants it and I'm the blocker.

- [ ] Clean out newly visible (because I just realized that we can use GitHub's global issue search) [multi-repo PR queue](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Agratipay). Internal pressure because I want clean queues.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-06/?msg=35922620&page=1)

**Comment by Changaco** [comment]
We've just landed two things that we should announce: the friend finder and the Italian translation.

**Comment by whit537** [comment]
Do we have a Twitter handle for whomever did the Italian translation? That sounds like a tweet to me.

Friend finder is blog-worthy but I think we should clean up the dashboard first.

**Comment by whit537** [comment]
I think we also owe our users a blog post about #67.

**Comment by whit537** [comment]
... because that's [a significant "hazard" that deserves a little "outrage."](http://www.psandman.com/index-PA.htm)

**Comment by rohitpaulk** [comment]
> I think we also owe our users a blog post about #67.

That was merged almost a year ago, why do you want to blog about it now? How is it a 'hazard'?

**Comment by whit537** [comment]
Sorry, wrong repo: https://github.com/gratipay/gratipay.com/issues/67.

**Comment by whit537** [comment]
[radar 2](https://github.com/gratipay/inside.gratipay.com/issues/184)
