### ISSUE TITLE
radar 2

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#184]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/176)

**Comment by whit537** [comment]
Ping @Changaco @rohitpaulk @techtonik et al.

**Comment by whit537** [comment]
Here's what's on my radar this week, and why:

- [ ] Keep driving the migration away from **Balanced** (https://github.com/gratipay/gratipay.com/issues/67). External pressure because they're going out of business in [59 days](https://daycalc.appspot.com/06/11/2015) and migrating is risky and a lot of work.

- [ ] Wrestle with big questions occasioned by Balanced going out of business: https://github.com/gratipay/inside.gratipay.com/issues/180. It turns out that regulatory compliance and business clarity converge. :-) External pressure because Balanced is going out of business. Internal pressure because I want clarity.

- [ ] Get card charge notifications out there (https://github.com/gratipay/gratipay.com/pull/3301). Didn't make it for PyCon but it's at the end of the pipeline and I've been reviewing it so far. Internal pressure because I want it and external because I started reviewing it.

- [ ] Tweak our **work process** (https://github.com/gratipay/inside.gratipay.com/issues/163). We almost landed this two weeks ago but then the pk id/username issue surfaced so there's still a bit more work to do here. Internal pressure because I'm torqued and embarrassed about Gratipay right now and I can't make it something I'm proud of all by myself. I need you. :-)

- [ ] Work down our [security queue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+label%3ASecurity). I want to get down to **Security 0** and then write a blog post about it. "Security is important to us. We run at Security 0." Internal pressure because running at Security 0 to me is like cleaning the toilet or brushing my teeth or compiling with no warnings. It's just the right way to operate. I've seen some open-source projects with a *lot* of open security issues. It's a case of queue collapse (you're overwhelmed, you're never gonna dig out). I don't want to ever reach that point. Let's get to Security 0 while we still stand a chance, so we can stay there and be good citizens.

- [ ] Organize the **redesign** (https://github.com/gratipay/gratipay.com/issues/3248). This is a big project. https://github.com/gratipay/gratipay.com/issues/3220 and the new [Product](http://inside.gratipay.com/big-picture/product) page were prerequisites. 3220 kicked out a number of issues, next step is to start organizing the work here. Internal pressure because I'm torqued and embarrassed about our product and I see this as the project that's going to turn it into something I'm proud of.

- [ ] Deal with **https://github.com/gratipay/postgres.py/pull/43**. External pressure because @Changaco wants it and I'm the blocker.

- [ ] Clean out newly visible (because I just realized that we can use GitHub's global issue search) [multi-repo PR queue](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Agratipay). Internal pressure because I want clean queues.

- [ ] Solidify **marketing plan** (https://github.com/gratipay/inside.gratipay.com/issues/177). Internal pressure because I want more people to be using Gratipay.

**Comment by techtonik** [comment]
Me is still struggling to remove the obstacles for development setup:

- [ ] https://github.com/gratipay/gratipay.com/issues/3165 - it is critical to get rid of symlinks to simplify setup. I don't see dealing with Git hack on top of symlink hacks on top of Aspen hacks as a way to go with development. Need help with removing dependency on filesystem from Gratipay. There is a big problem with simplates that there is no recipe book - http://aspen.io/simplates/ - it is not clear how to place a redirect to another page or how to include another template.

- [ ] https://github.com/gratipay/inside.gratipay.com/pull/133 - play inside.gratipay.com, rename a colophon page to test how it works, then do the same for the main site, get back :octocat: and twitter icons, add TL;DR to tools, try to fix design nits

- [ ] epic task - get a prototype app based on elsewhere to learn how to deal with OAuth - registration without email, query email, login with OAuth, request additional permissions per operation

- [ ] https://readthedocs.org/ - see if GP can provide an API to power such things

- [ ] pay out some Bitcoins

**Comment by whit537** [comment]
I'm slowly reading http://mako.cc/writing/funding_volunteers/funding_volunteers.html.

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/190)
