### ISSUE TITLE
radar 3

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#190]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/184)

**Comment by whit537** [comment]
Here's what's on my radar this week, and why:

- [ ] Start coding on the migration away from **Balanced** (https://github.com/gratipay/gratipay.com/issues/67). External pressure because they're going out of business in [52 days](https://daycalc.appspot.com/06/11/2015) and migrating is risky and a lot of work.

- [ ] Keep wrestling with **big questions** occasioned by Balanced going out of business: https://github.com/gratipay/inside.gratipay.com/issues/180. It turns out that regulatory compliance and business clarity may converge! :-) External pressure because Balanced is going out of business. Internal pressure because I want clarity.

- [ ] Work down our [security queue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+label%3ASecurity). I want to get down to **Security 0** and then write a blog post about it. "Security is important to us. We run at Security 0." Internal pressure because running at Security 0 to me is like cleaning the toilet or brushing my teeth or compiling with no warnings. It's just the right way to operate. I've seen some open-source projects with a *lot* of open security issues. It's a case of queue collapse (you're overwhelmed, you're never gonna dig out). I don't want to ever reach that point. Let's get to Security 0 while we still stand a chance, so we can stay there and be good citizens.

- [ ] Organize the **redesign** (https://github.com/gratipay/gratipay.com/issues/3248). This is a big project. https://github.com/gratipay/gratipay.com/issues/3220 and the new [Product](http://inside.gratipay.com/big-picture/product) page were prerequisites. 3220 kicked out a number of issues, next step is to start organizing the work here. Internal pressure because I'm torqued and embarrassed about our product and I see this as the project that's going to turn it into something I'm proud of.

- [ ] Clean out newly visible (because I just realized that we can use GitHub's global issue search) [multi-repo PR queue](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Agratipay). Internal pressure because I want clean queues.

**Comment by whit537** [comment]
P.S. Today is the only day I'm fully available this week.

**Comment by whit537** [comment]
Ping @rohitpaulk @techtonik @kaguillera et al. What's on your radar?

**Comment by whit537** [comment]
Had a short call with @rohitpaulk (though he had no mic). Sounds like we're going to try augmenting these radar tickets with Hangouts at 13:30 UTC on Mondays.

**Comment by kaguillera** [comment]
Working on #3171 unless you have something more pressing that you need me to look at

**Comment by whit537** [comment]
Sounds good, @kaguillera.

P.S. Different repo: https://github.com/gratipay/gratipay.com/issues/3171.

**Comment by rohitpaulk** [comment]
- [ ] Get https://github.com/gratipay/gratipay.com/pull/3355 (send apology emails to the people we resent emails to) out the door, which'll solve https://github.com/gratipay/gratipay.com/issues/3352#issuecomment-94435599. @whit537 - Need your help with the email text, the script is done. 

- [ ] Work on https://github.com/gratipay/gratipay.com/issues/3295 (Add exchange routes to record-an-exchange.spt) with https://github.com/gratipay/gratipay.com/issues/2779 (backfill the routes and status columns of exchanges, constrain to NOT NULL) as the end goal. Currently, the only places where new exchanges are added without a `route` or `status` parameter are **(1)** MassPay, and **(2)** record-an-exchange.spt. Since **(1)** uses **(2)**, solving **(2)** makes it easier to tackle **(1)**. Ideally, we want every single exchange to be recorded through `record_exchange` and `record_exchange_result`. 

That's all I can think of right now, I'll add to this when something new pops up.

**Comment by whit537** [comment]
> Need your help with the email text, the script is done.

Roger. Will look at that after lunch.

Re: exchange tracking ... awesome. That all needs to get cleaned up before we can migrate and from here it looks like a fair chunk of work, so that's great to have you working on that.

**Comment by whit537** [comment]
I am out the rest of the week, consulting. I will check in periodically but won't be getting a lot done.

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/191)
