### ISSUE TITLE
radar 4

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#191]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/190)

**Comment by whit537** [comment]
Here's what's on my radar this week, and why:

- [ ] Work on a **Braintree** PR (https://github.com/gratipay/gratipay.com/issues/3287). External pressure because Balanced is going out of business in [45 days](https://daycalc.appspot.com/06/11/2015).

- [ ] Keep **big questions** simmering: https://github.com/gratipay/inside.gratipay.com/issues/180. External pressure because apparently some companies think we're a compliance risk. Internal pressure because I want clarity.

- [ ] Work down our [security queue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+label%3ASecurity). I want to get down to **Security 0** and then write a blog post about it. "Security is important to us. We run at Security 0." Internal pressure because running at Security 0 to me is like cleaning the toilet or brushing my teeth or compiling with no warnings. It's just the right way to operate. I've seen some open-source projects with a *lot* of open security issues. It's a case of queue collapse (you're overwhelmed, you're never gonna dig out). I don't want to ever reach that point. Let's get to Security 0 while we still stand a chance, so we can stay there and be good citizens.

- [ ] Organize the **redesign** (https://github.com/gratipay/gratipay.com/issues/3248). This is a big project. https://github.com/gratipay/gratipay.com/issues/3220 and the new [Product](http://inside.gratipay.com/big-picture/product) page were prerequisites. 3220 kicked out a number of issues, next step is to start organizing the work here. Internal pressure because I'm torqued and embarrassed about our product and I see this as the project that's going to turn it into something I'm proud of.

- [ ] Clean out newly visible (because I just realized that we can use GitHub's global issue search) [multi-repo PR queue](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Agratipay). Internal pressure because I want clean queues.

**Comment by kaguillera** [comment]
Working on (https://github.com/gratipay/gratipay.com/issues/3171). Issue (https://github.com/gratipay/gratipay.com/issues/#2534) to be more specific.

**Comment by techtonik** [comment]
Waiting for somebody to merge https://github.com/gratipay/gratipay.com/pull/3363

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/195)
