### ISSUE TITLE
revise model

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#192]
Stripe has [raised the specter](https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973) that we might be engaged in unlicensed money transmission:

> The crux of the problem is the stored value: holding funds in a balance that can then be redistributed, in our opinion, qualifies as money transmission, which we cannot support. There are other compounding factors that would make it hard to reason around this property, for example the lack of a concrete product or service being provided.

Over on https://github.com/gratipay/gratipay.com/issues/3321 we learned that a money transmitter is "a business, Business A, that accepts money from Person B and transmits that money to Person C, either at a later time or a different place." We also learned that it's expensive to get licensed (we certainly can't afford it), and that companies have gotten flipped over this in the recent past. Sooooo let's not be a money transmitter! :-)

Stripe suggests two properties of Gratipay that make it a money transmitter:

 - we allow funds to pool indefinitely 
 - payments are undirected ("no strings attached")

Is it true that these two properties put us at risk of FinCEN or NYDFS coming after us? What about other properties, such as taking in payments via credit card and paying out via bitcoin?

**Comment by whit537** [comment]
Moving to a private repo, per #193.

**Comment by whit537** [comment]
Okay, returning from private discussion with @copiesofcopies. Reopening to track the public side of this, I'll continue to communicate with @copiesofcopies privately.

**Comment by whit537** [comment]
Where to start? Here is [a helpful glossary](http://www.ecfr.gov/cgi-bin/text-idx?SID=a457db49113d5f8ca45f5252dd7dced0&mc=true&node=se31.3.1010_1100&rgn=div8) that sets out the following taxonomy under U.S. law:

 - **financial institution**
  - bank (except bank credit card systems)
  - broker or dealer in securities
  - **money services business**
    - dealer in foreign exchange
    - check casher
    - issuer or seller of traveler's checks or money orders
    - provider of prepaid access
    - **money transmitter**
    - U.S. Postal Service
    - seller of prepaid access
  - telegraph company
  - casino
  - person subject to supervision by any state or Federal bank supervisory authority
  - futures commission merchant
  - introducing broker in commodities
  - mutual fund

The definition of a money transmitter is simple and broad: 

>*Money transmitter—(i) In general.* (A) A person that provides money transmission services. [...]
>
(B) Any other person engaged in the transfer of funds.

There are six possible exceptions to the money transmitter definition, two of which are interesting to us:

> (ii) *Facts and circumstances; Limitations.* Whether a person is a money transmitter as described in this section is a matter of facts and circumstances. The term “money transmitter” shall not include a person that only:
>
(B) Acts as a payment processor to facilitate the purchase of, or payment of a bill for, a good or service through a clearance and settlement system by agreement with the creditor or seller;
>
(F) Accepts and transmits funds only integral to the sale of goods or the provision of services, other than money transmission services, by the person who is accepting and transmitting the funds.

These are the "payment processor exemption," and the "goods and services exemption."

The way the latter would work is that we would insert ourselves more full into the delivery process. For example, we might verify that open source projects deliver legitimate releases before releasing funds (think: Kickstarter project completion).

The former, the payment processor exemption, seems to me to be a more natural fit for Gratipay, and this seems to be the one Stripe is trying to fit us into. Here's FinCEN's comment in [a big 2011 publication](http://www.gpo.gov/fdsys/pkg/FR-2011-07-21/pdf/2011-18309.pdf):

>Although payment processors may provide a money transmission service, the service is ancillary to their primary business of coordinating payments either from a debtor to a creditor or, if operating at the point of sale, from a purchaser to a merchant. A payment processor could not provide the primary service of coordination without providing ancillary money transmission services, but because the money transmission services are ancillary, and because they are generally low risk, it is appropriate for entities
engaged in this activity to be excluded from the definition. Note, however, that this limitation only applies to transmission services by payment processors on behalf of the creditor or seller and not the debtor or buyer. A contractual agreement for transmission services between the creditor or seller and the money transmitter is a relatively controlled flow of money that poses little money laundering risk, provided that the funds are transmitted only to the creditor or seller with whom the payment processor has contracted and not to another location or person. 

And here are the four criteria they seem to have settled on in their requests for ruling ([e.g.](http://www.fincen.gov/news_room/rp/rulings/html/FIN-2014-R009.html)):

 1. the entity providing the service must facilitate the purchase of goods or services, or the payment of bills for goods or services (other than money transmission itself);
 1. the entity must operate through clearance and settlement systems that admit only BSA-regulated financial institutions;
 1. the entity must provide the service pursuant to a formal agreement; and
 1. the entity’s agreement must be at a minimum with the seller or creditor that provided the goods or services and receives the funds.

Points 3 and 4 we already have, and if we don't it should be a straightforward update to our terms. Point 2 means forgoing bitcoin (that's okay, we've only done 4 bitcoin payouts vs. 516 ACH credits and 468 PayPal payouts since we started keeping better track with https://github.com/gratipay/gratipay.com/pull/3282). Point 1 is the more interesting part. This is the part where we need to attach strings, or as Stripe put it at https://github.com/gratipay/gratipay.com/issues/3324#issuecomment-93562216, "make it clear that this is intended to support actual services."

**Comment by whit537** [comment]
The basic idea here with the payment processor exemption is that we would implement an application process to become a receiver on Gratipay, and we would vet applicants based on what they were receiving money for. This gives us a chance to vet for brand fit (#187). We also want to require a working payout route, and since we're going to have everyone reapply anyway we can reprompt for payout info since it looks at https://github.com/gratipay/gratipay.com/issues/3379#issuecomment-100051650 like we won't be getting that from Balanced.

**Comment by whit537** [comment]
This also lines up with narrowing our focus (#180).

**Comment by bayprogrammer** [comment]
I'm not sure if it really relates, but it keeps popping in my mind, so I'll mention it here. The donation model of Vim specifically avoids a "direct relationship" between Bram's work and doners, so that Bram doesn't incur tax liability for money he passes directly to charity. Perhaps relevant as you consider how the new proposed model might impact uses.

> I donated $$$, now please add feature XYZ!

> There is no direct relation between your donation and the work Bram does. Otherwise you would be paying for work and Bram has to pay income tax over the donation. If you want to hire Bram for specific work, contact him directly, don't use the donation system.

Source: http://www.vim.org/sponsor/faq.php

I'm guessing that sort of arrangement isn't what Gratipay is really about, but I figured I'd bring it up just in case it's relevant.

**Comment by whit537** [comment]
Thanks for the brainstorm, @bayprogrammer.

**Comment by sc0ttkclark** [comment]
Concerning for sure, but excited to see where this lands. I really liked how Gratipay works!

**Comment by Changaco** [comment]
I was hoping I wouldn't have to fork Gratipay, but every day it's looking more and more like I'm gonna have to.

**Comment by lpalgarvio** [comment]
@Changaco, without knowing much about gratiplay or the development efforts, or any of you developers, I ask that You put Your energy into constructive thinking and discussion, instead of making claims.

If You want to fork it, just fork it. But please don't come here with this kind of attitude.
If I was any of the admins of the project and had power, your comment would had been erased the moment it was posted. It's inconstructive, disrespectful and conflictuous, and add nothing good to the project.

**Comment by Changaco** [comment]
The members of the Gratipay team know that I am never intentionally non-constructive, disrespectful or conflictive. As a matter of fact my comment was intended to be the opposite: even though I have no obligation to inform the Gratipay team of a possible fork, I feel it is more respectful and less conflictive to do so than to keep it secret.

**Comment by rohitpaulk** [comment]
> The members of the Gratipay team know that I am never intentionally non-constructive

https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100152330 sure did seem disrespectful and non-constructive to me. "I'm going to fork Gratipay, I thought I'd let you know" would have been respectful and less conflictive :)

**Comment by lpalgarvio** [comment]
It's not the matter of making a fork or announcing/not announcing it to them.
It's announcing it publicly on their issue queue/project space.

That is like receiving an invitation to a friend's party. and then publicly decline it, with a paper in front of their house, saying you have better plans. It's not polite nor respectful.

To be polite and respectful, you would announce it first, privately to the developers, then publicly, but not here, and not in this way, with this kind of speech. I wonder if a "here's a fork" new issue would be correct.

But it's my opinion.

**Comment by mw44118** [comment]
Just came here to say that I hope this doesn't stop the project.  Gratipay is exciting!

**Comment by Changaco** [comment]
Maybe the comment could have been worded better, in any case I see no point in discussing this further, Chad will delete my comments if he doesn't like them.

**Comment by whit537** [comment]
@lpalgarvio Changaco has a long history with the project, and was in fact our top developer until [recently](http://changaco.oy.lc/blog/goodbye-gratipay/). He's well-known around here and I see no problem with his comment, nor with him forking. We've had one fork already, and we were happy to try to help them (https://github.com/gratipay/inside.gratipay.com/issues/70).

@Changaco Thanks for the heads-up. It does seem like there's room for a Gratipay alternative for the (as I'm reading it) hard-core libertarian crowd. If you decide to fork, let us know how we can help. :-)

**Comment by tshepang** [comment]
@whit537 why would you want to help with the fork?

**Comment by whit537** [comment]
@tshepang Why wouldn't I? @Changaco is great, and I want to see him succeed. I made the same offer to the previous fork (#70).

**Comment by whit537** [comment]
A user [writes](https://gratipay.freshdesk.com/helpdesk/tickets/2100):

>My volunteered vote as a customer is for you to switch to bitcoin.
I know there may be issues that I am not aware of in regards to the marriage of bitcoin to your business (other than ubiquity of dollars vs bitcoin's relatively minor market share as a transfer of value) but if it was possible for you, especially seeing as how USD and our fiat currency system (and the relevant regulation) is failing to provide flexibility to a legitimate business model such as yours, your customers like myself will continue to support you.
Its a stretch I know, especially not being the one that would have to do the work that you are faced with, but perhaps this can even turn out for the better for Gratipay.  Here's hoping!

**Comment by tshepang** [comment]
@whit537 it's a strange offer, given the limited resources. It's one thing to wish someone succeed, and it's another to help them do so with a competing product. That is, since Gratipay is your (our) product, you likely to believe it's better than any fork.

**Comment by whit537** [comment]
@tshepang Let's be clear: I'm not offering to work on the fork apart from Gratipay. I'm offering (as I did at #70) to consider suggestions for actions on Gratipay's side that would make the fork's life easier as it gets started. We're off-topic here, though, and I trust @Changaco to initiate conversations for anything he might find helpful from us.

**Comment by tshepang** [comment]
is kool

**Comment by colindean** [comment]
> My volunteered vote as a customer is for you to switch to bitcoin. 

A welcome suggestion, but it's a horse well-beaten˚. Gratipay's current workflow would still likely classify it as a money transmitter, and Gratipay should not be ever holding anyone's private keys. 

<boromir.jpg> One does not simply switch to Bitcoin. 

_˚ I think I've held the heaviest stick for those beatings; it's how I got involved in the first place._

**Comment by Changaco** [comment]
@whit537 :-) It's not really about politics/governance, the interest seems to be for a European alternative, with a legal structure that matches the philosophy of the project as an extra good point.

At this time I'm still only thinking about it and discussing it with the people who are interested.

**Comment by lpalgarvio** [comment]
@whit537 great words!

on topic,
I think it should be easy to work with an alternative currency (bitcoin), but can be hard to convince people to use it.
Using third party services (paypal, visa, etc) can also be seen as an easier method out of this.
I imagine that trying to establish as a kind of bank entity can be a very troublesome process.

**Comment by JanelleOrsi** [comment]
I'm not caught up on this thread, but the Sustainable Economies Law Center contributed to comments on money transmission laws in CA in NY. We recently [made some progress](http://www.theselc.org/david_and_goliath_and_mta) in CA to exempt 501(c)(3)s from the law. It's a start. [More info here.](http://www.communitycurrencieslaw.org/financial-and-banking-laws/#Comments_on_Proposed_California_MTA_Rules) Someone should do an expose on these laws and how big companies like American Express, PayPal, etc advocated for them in the name of consumer protections, but more likely in order to destroy competitors.

**Comment by copiesofcopies** [comment]
@JanelleOrsi I'd love to talk to you about SELC's work on this issue. Can I contact you via email?

**Comment by techtonik** [comment]
@lpalgarvio I am :+1: with @Changaco that I don't want Gratipay to die just because of stupid U.S. regulations that don't cover donation services. If it needs to be forked somewhere else, let's be it. U.S. needs a better definition of "money laundering" and what do they want to prevent.

I don't need lawyers citing me the laws. I need to know the reason, why giving to others is all of the sudden illegal. Gratipay is an open and transparent platform, so I don't see any problem with detecting "money laundering" as long as we are not giving out the personal data for no reason.

If there is something that kills the economy, makes people out of jobs and kills, let's discuss that, but saying "no, you can't continue, because it is illegal" is mean. If U.S. proves that Gratipay is evil, we can work from that point and improve, but just stating that it is illegal is a non-fair game.

**Comment by whit537** [comment]
@techtonik The U.S. pretty clearly wants to prevent the channeling of funds to their enemies around the world, and I'm perfectly comfortable with that. I think we can find a way to satisfy the requirements of U.S. law and still preserve the "ideology, spirit and model of the project" as @lpalgarvio puts it.

**Comment by techtonik** [comment]
@whit537, so if funds are not crossing U.S. country border, everything is fine, right?

**Comment by whit537** [comment]
#### A Word about Lawyers

As part of the [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), we're figuring out how our company is going to handle legal issues. It turns out that a lawyer (in the U.S., at least?) is simply not permitted to provide legal advice publicly, due to a fundamental constraint of the U.S. legal system called [attorney-client privilege](http://en.wikipedia.org/wiki/Attorney%E2%80%93client_privilege). The purpose is to enable lawyers and their clients to have "full and frank" discussions together, so that the lawyer can provide the best advice and representation possible. In other words, we can't pay @copiesofcopies enough to post his advice here in public.

One option for us is to not use lawyers. DIY law. I don't dismiss that idea as quickly as most will, but I do dismiss that idea. Gratipay is not going to not have a lawyer.

Now, it's Gratipay's privilege to publish our lawyers' advice, wholesale or in part, so another option is to accept @copiesofcopies input privately, but mirror it publicly. Aaron and I have spent a fair bit of energy over the past week discussing this possibility. At the very least, this goes against the grain of the entire legal profession. I'm not sure we'd find a lawyer more willing to countenance the thought than Aaron, and I can tell you that he is *not* comfortable with it. The possibility that I might publicly disclose our entire conversation over the past week has added a mild level of stress and friction, and discussing this meta concern has distracted us from addressing the immediate issues upon which Gratipay's future in fact hinges. Having a permanently mildly strained relationship with our counsel is not in Gratipay's best interest.

Moreover, the fact is that I've *always* privately deliberated about Gratipay's decisions. You can't read my mind (yet?), and of course I consider possibilities and choose my words when posting publicly. That's simply unavoidable. As Gratipay grows, the scope of private deliberation needs to expand beyond my head. Sooner or later we're going to need to bring on new owners (whether via #72, #196, or #197). With more than one owner&mdash;I'd rather we use the term "steward" or "trustee," to be honest&mdash;we'll need to carve out a sphere of communication that is private to them. Granting the existence and legitimacy of this sphere, the U.S. legal system with its [attorney-client privilege](http://en.wikipedia.org/wiki/Attorney%E2%80%93client_privilege) is as good an implementation as any for Gratipay's purposes.

We have well-established policies for handling user feedback and data privately ([support](http://inside.gratipay.com/howto/support-users), [safety](http://inside.gratipay.com/howto/deal-with-bad-behavior), [violations](http://inside.gratipay.com/howto/handle-terms-violations)), as well as [security](http://inside.gratipay.com/howto/handle-security-issues) issues. I accept the need to also have a sphere of shared private deliberation amongst the stewards of Gratipay and our counsel.

**Comment by whit537** [comment]
My goal at this point is to return to processing next week. Here are the things that need to happen in order for that to take place:

 1. [ ] We review and consolidate our [Terms & Conditions](https://gratipay.com/about/policies/terms-and-conditions) and [Terms of Service](https://gratipay.com/about/policies/terms-of-service) (https://github.com/gratipay/gratipay.com/issues/3367).
 1. [ ] We write a separate agreement for receivers on Gratipay (https://github.com/gratipay/gratipay.com/issues/3390).
 1. [ ] We implement an application process for receivers that includes a) accepting the new receiver terms, and b) whitelisting by Gratipay; and we modify payday to only process payments for accepted receivers (https://github.com/gratipay/inside.gratipay.com/issues/187).

I will continue to work privately with @copiesofcopies, with the results of our deliberations reflected on the public tickets.

**Comment by techtonik** [comment]
> At the very least, this goes against the grain of the entire legal profession.

Because the core value of this profession was driven historically by the need of people to rule conflicts without shooting each other. Back in 19th century there was no two way public communication channels like we have. And people need legal advice just to access the information. When access to laws became free and computer systems allowed to deal with structure complexity, access and indexing of information no longer provided a value. But legal people want to preserve their jobs and they are in charge. In Belarus the online access to laws is through SMS paywall and you need to buy a license if you want to publish the raw texts. And it is just to cover "hosting" as they say it - it is not a price for laws development.

I wouldn't mind against those guys playing their games, but they actually create more obstacles than value. Instead of telling people, what is the required budget, how to improve the process, they just force you to pay or suffer with FUD. I feel sympathy for people who were replaced by automation machines, but I don't feel sympathy for professions that make other people suffer.

> Having a permanently mildly strained relationship with our counsel is not in Gratipay's best interest.

Yes. I understand that the peer pressure could be disadvantageous to any person who would step in to be different from the other. And it is not about bias and inequality, it may have economic consequences. And if that risk is real, it seems that EFF is the only option for us.

> Founded in 1990, EFF champions user privacy, free expression, and innovation through impact litigation, policy analysis, grassroots activism, and technology development. 

https://www.eff.org/about

**Comment by elliottw** [comment]
sorry for coming in late, but I also think it might make sense to look into For Benefit Of accounts. I'm working on another project where the company basically manages accounts in the names of all the users of that service instead of holding any money for any amount of time in the company's name. Not sure if this is helpful, but at least giving some info I haven't seen in the thread yet.

**Comment by mitar** [comment]
Why don't you partner up with [Internet Archive](https://archive.org/) and their [Internet Credit Union](https://internetcreditunion.org/)? They have a banking license, are interested in supporting new initiatives, they even had a bitcoin support and they have bitcoin ATM in Internet Archive itself, and they are known on being willing to fight legislation.

So instead of having to change your processes, you could partner with a bank which would officially do all the money transmission work, while you would be a nice user interface on top. And Internet Credit Union does need a nice user interface on top. :-)

**Comment by whit537** [comment]
> Why don't you partner up with Internet Archive and their Internet Credit Union?

Sounds like a +1 for https://github.com/gratipay/gratipay.com/issues/3322, eh? I reached out to IAFCU a couple weeks ago in the context of https://github.com/gratipay/gratipay.com/issues/3372 and have not heard back. They ended up pulling the plug on their bitcoin initiative so I'm not sure how stable a relationship it would be.

**Comment by whit537** [comment]
> I also think it might make sense to look into For Benefit Of accounts.

Thanks for putting this on the radar, @elliottw. 

http://www.citibank.com/transactionservices/home/public_sector/docs/pbo.pdf
http://en.wikipedia.org/wiki/Custodial_account

Seems like the model here would be that Gratipay has multiple bank accounts, one for each receiver? That's potentially interesting for the long term, but I don't think it's realistic in terms of getting processing back on track by next Wednesday.

**Comment by elliottw** [comment]
yeah, long term for sure. i just wanted to put that out there. the co i'm working with is setting up a FBO for each user of their system so if they go under, all the money is still in the names of the individual users. for long term, i think this would be a really good solution.

**Comment by whit537** [comment]
Another point: I view our [Teams](https://gratipay.com/about/features/teams/) feature as essentially a payroll product (https://github.com/gratipay/gratipay.com/issues/2569). That feature is awesome and interesting. It's also [not widely used](https://gratipay.com/explore/teams/) and to my mind probably has compliance implications that we don't understand right now. I propose that we drop it for now. The only two viable teams right now are:

https://gratipay.com/Gratipay/
https://gratipay.com/DrupalCoreGittipTeam/

We'll simply have to let funds settle to a bank account and distribute to team members outside of Gratipay.

cc: @YesCT for DrupalCore.

P.S. Maybe FBO accounts are interesting in the team/payroll context when we revisit?

**Comment by mitar** [comment]
> I reached out to IAFCU a couple weeks ago in the context of gratipay/gratipay.com#3372 and have not heard back.

How you reached to them? E-mails are not the best way with them.

The best is to go to Internet Archive in person. They have open weekly staff meetings/lunch every Friday at noon. Go there, you get free food, everyone at Internet Archive says what they were doing that week, you tell what you are doing, you find to whom you want to talk to and then you go after the lunch and talk to the person or people you want to do something with.

It is a very interesting approach of running an open non-profit in my opinion. You could also get an interesting experience how you could do Gratipay in the future as it grows. So this open meetings anyone can attend is really an interesting idea. Also very useful for learning what they do and finding ways to do things together.

But yea, e-mails do not work really. :-)

> They ended up pulling the plug on their bitcoin initiative so I'm not sure how stable a relationship it would be.

Yes, that was the regulators pressure about anonymity around bitcoin (and thus financing terrorism). But at least they already have licenses you would need for normal accounts. So that is a different thing. There they would not have to go against the regulators. They would already do what they have licenses to do, and you would just work with them.

Sadly, you just missed the Friday lunch today.

**Comment by whit537** [comment]
> The best is to go to Internet Archive in person.

~7 hrs from me? Happy to but not this week. :-)

**Comment by mitar** [comment]
Delegate. :-)

**Comment by whit537** [comment]
@mitar You are brilliant. :dancer: You live close, then? Want to go for us next Friday? :poultry_leg: :smile:

**Comment by elliottw** [comment]
@whit537 I was planning on moving all "part time" coworking space members at CatapultPGH to gratipay donation only (30+ members) and all new members of the coworking space, and I was going to start taking a salary from Catapult, after 4 years.

Just saying there was going to be three teams ;)

**Comment by whit537** [comment]
@elliottw That's awesome! Catapult definitely is on the list of prime example receivers we want on Gratipay. Does it work for you to drain that to a Catapult bank account and take your salary from there?

**Comment by elliottw** [comment]
@whit537 the manual draw is a problem for us because there is no such thing as a "community" bank account, so it's hard to manage varied people drawing varied amounts of money without having complete access to the bank account, let alone easy transparency. 

The only alternative I've found so far, as apposed to using gratipay, is a debt card not connected to a bank account (e.g. https://www.bluebird.com/) with "child debt cards" that have set allowances. This is obviously non-optimal for so many reasons :(

My 18 month goal is to move Catapult as close to possible towards an "Open Space", inline with your Open Company and all the other Open's. 

You gotta do what you gotta do, it's unfortunate that gratipay is the only thing remotely similar to a community bank account.

**Comment by whit537** [comment]
@elliottw Sorry. :-/ We'll get there, but we have to [do it right](http://c2.com/cgi/wiki?MakeItWorkMakeItRightMakeItFast):

1. Make it work.
1. Make it right. ← **We are here.**
1. Make it fast.

**Comment by elliottw** [comment]
You're doing a good job. We'll figure it out in the meantime.

**Comment by whit537** [comment]
@elliottw Thank you, sir. You, too! :-)

**Comment by whit537** [comment]
P.S. I've added Catapult to https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100361153. :)

**Comment by elliottw** [comment]
awesome

**Comment by mitar** [comment]
> @mitar You are brilliant. :dancer: You live close, then? Want to go for us next Friday? :poultry_leg: :smile:

You would just delegate to unknown random fish on GitHub? ;-)

**Comment by whit537** [comment]
> You would just delegate to unknown random fish on GitHub? ;-)

To ask Jordan Modell to check his email? Sure! :-P

**Comment by YesCT** [comment]
We are looking at moving to another platform. Do we have a couple weeks, or
is it more urgent? -c

**Comment by whit537** [comment]
@YesCT It's [more urgent](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8). We have stopped processing payments, and in order to be included when we start processing again (we're aiming for next week, so only one week lost), you would need to coordinate with us to accept our new terms of service, which are currently [under development](https://github.com/gratipay/gratipay.com/issues/3390). At this point, if you do nothing, then we won't be processing any more payments for you. I'm really sorry for the abrupt change. :-(

**Comment by anoxic** [comment]
@whit537, I have a suggestion along the lines of @elliottw's *For Benefit Of accounts*. I have used GoFundMe in the past, who use the [WePay](https://www.wepay.com/) service. They are a payment service provider that offers a "flexible payments api". The nice thing about their model is that they specifically work with crowdfunding platforms. They would place themselves in as the payment services provider while Gratipay would simple interface with their API to facilitate the connection. Each contributer and payee would have a direct connection between each other through WePay (and every payee would need a WePay account where they link their bank account for deposit).

You may also be able to facilitate a similar direct connect using other payment aggregators like PayPal, [Dwolla](https://www.dwolla.com), [Venmo](https://venmo.com/), or maybe even [Square Cash](https://cash.me/), but it looks like this is WePay's target market.

This may not solve your immediate problem, since you would have to migrate to a new API, but could be a more long-term solution.

**Comment by whit537** [comment]
Thanks @anoxic. We're [aware](https://github.com/gratipay/gratipay.com/issues/69) of WePay (I've added a +1 for you over there). From a *technical* perspective things seem to be coming together for us around [Braintree](https://github.com/gratipay/gratipay.com/issues/3287) for credit cards, and [Citizens](https://github.com/gratipay/gratipay.com/issues/3366) for ACH. What we're talking about on this ticket is the *legal* foundation for our business.

**Comment by mitar** [comment]
What about https://www.skrill.com/? Flattr is using them.

**Comment by whit537** [comment]
@mitar Again, the challenge on this ticket is not technological. It's legal. We have a new technology stack coming together to replace Balanced; see https://github.com/gratipay/gratipay.com/issues/3377.

**Comment by mixolidia** [comment]
I've been reading all the comments. So to be clear, if you are an individual (not incorporating or corporation) you won't be able to receive donations through Gratipay?

I'm confused how it is illegal since, through PayPal, people can send money (donation) to friends and family without paying a fee. Except that these donations can not be scheduled, as far as I know.

**Comment by anoxic** [comment]
@whit537 - what @mixolidia is saying is similar to what I was trying to get at. Although I mentioned some particular platforms, that was as an example. What I mean is this: rather than charging cards and rolling everything into a bank account where it is later transferred elsewhere, let the users have a "direct connection" with each other, through something like Dwolla or Paypal or Wepay. All Gratipay would do is facilitate the amount and schedule, the funds would transfer directly between the payer and payee.

Am I missing something here?

**Comment by whit537** [comment]
> I'm confused how it is illegal since, through PayPal, people can send money (donation) to friends and family without paying a fee.

@mixolidia PayPal has [money transmitter licenses](https://www.paypal.com/webapps/mpp/licenses).

> So to be clear, if you are an individual (not incorporating or corporation) you won't be able to receive donations through Gratipay?

If you've been using Gratipay to receive donations from friends and family, then unfortunately we're not going to be able to support that under [our new terms](https://github.com/gratipay/gratipay.com/issues/3390). I'm sorry. :-(

> Except that these donations can not be scheduled, as far as I know.

Actually, I know I've seen monthly subscriptions through PayPal, though I'm not sure exactly how to set that up. You might also look into [Recurrency](https://recurrency.us/) and [Moonclerk](http://www.moonclerk.com/), as well as [Patreon](https://www.patreon.com/)'s "monthly" option.

----

Going forward, what Gratipay has to offer you is something we're calling "open work."

The direction Gratipay is [headed](https://github.com/gratipay/gratipay.com/pull/3400) is to promote Teams to a first-class entity. A Team will be a group of people working together to deliver a product or service, and Teams will be able to receive payments and distribute funds to their members.

Only Teams will be able to receive payments directly. That said, it will definitely be possible to have a Team with only one member (the Owner), and we are [planning](https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101000562) to offer a migration path for current Gratipay users to create a Team and redirect the tips that were directed to them, to the Team. This migration path should be workable for many of the individuals using Gratipay, since most of them were receiving money on Gratipay in view of one or more products and services they deliver (open-source software, mostly).

Teams will be required to clearly state how others can get involved with the work they do, and how any revenue is shared with contributors. Teams will be vetted and approved by Gratipay. The goal is to build Gratipay into a place where individuals can go to find open work&mdash;work they can start without having to go through a cumbersome hiring process, and yet get paid for (and feel good about!). This doesn't help with your immediate situation, @mixolidia, but that's what Gratipay has to offer you going forward. You'd be welcome to join [the Gratipay team](https://gratipay.com/Gratipay/), for example. :-)

**Comment by whit537** [comment]
> [L]et the users have a "direct connection" with each other, through something like Dwolla or Paypal or Wepay.

Tying ourselves to a specific platform could've been a way to preserve the genius grant idea (though it would've made sign-up harder), but as discussed at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100497390, "Legal concerns made us stop with our old model, but it's business vision that is driving our new model." This ticket ended up being about the legal concerns, while #180 was about the business vision. Looking back, I should've cross-posted https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100497390 here, especially since I directed people here in "[Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8)". Sorry. :-(

**Comment by mixolidia** [comment]
Thanks for your suggestions @whit537, I've been receiving donations for a personal project according to what the terms were when I signed up four months ago. I call them donations because people are not expecting any particular product in return. I do contribute to the tech community, there just is not one specific app. I did marketing on my own to receive funds in my Gratipay account. I mean I was on Gratipay and didn't start getting tips until I started telling people about it. I think I know some of them and some people have contacted to tell me about their support. But all my the tips are anonymous, so I can't contact them to let them know of the changes directly. And how the relationship they have with me through Gratipay may be affected.

I read how teams work on Gratipay, is that how they will still work moving forward? So if I migrate into a team the funds I fund-raised will be distributed equally among all team members? I'm very grateful for Gratipay's help with the transactions in my fund-raising for my projects. I'm just trying to be clear on my options since all these changes have really impacted my budget for next month.

**Comment by whit537** [comment]
> I read how teams work on Gratipay, is that how they will still work moving forward?

More or less. First draft of terms will drop soon on gratipay/gratipay.com#3390 and that'll have the details, so watch that ticket as well.

> So if I migrate into a team the funds I fund-raised will be distributed equally among all team members?

That's up to you. Gratipay Payroll has one distribution algorithm right now (and it's not "equal shares," it's "take what you want, kids eat first"). If you want a different distribution algorithm it's fine to do that outside of Gratipay. You'll just need to explain on your Team page what the distribution algorithm is. See gratipay/gratipay.com#3390 for more discussion of this.

> [T]hese changes have really impacted my budget for next month.

Yeah, I'm sorry. We're in the same :boat:, at least. :-(

> I've been receiving donations for a personal project

@mixolidia What's the project? What product or service is the project delivering? How can others get involved to help you with it? How will you share with contributors any revenue the project generates? As long as you've got solid answers to those questions (and can otherwise agree to our in-the-oven terms), then you can migrate your existing payments to a Team for your project. Let's find a way to make that happen! :-)

**Comment by whit537** [comment]
First draft of new terms is up at https://github.com/gratipay/gratipay.com/pull/3408.

**Comment by mixolidia** [comment]
@whit537 Thank you for your response. I think I can migrate, but I guess Gratipay will be the judge of that. Also, I've been following along today. Is there going to be an email to start the migration telling how? Or do I just go into my account and change to team?

**Comment by whit537** [comment]
> I think I can migrate

Huzzah! Happy to discuss your application here with you if you want, or privately on support@gratipay.com if you're more comfortable with that. Let's see if we can find a way to make it work. What's the project you're planning to apply with?

> Is there going to be an email to start the migration telling how?

We'll share a link when it's ready. You can follow along on https://github.com/gratipay/gratipay.com/issues/3399, that's where the action is and that'll be the first place we announce the application link. We are planning to run payday tomorrow with just a few teams, the ones paying close attention, such as yourself. We'll beta test the new system this week and then blast out an email and blog post ahead of next week.

**Comment by mixolidia** [comment]
Thank you! @whit537 I sent an email.

**Comment by whit537** [comment]
Okay! Applications for new teams are now open!

https://gratipay.com/new

**Comment by whit537** [comment]
With that, I'm going to close this ticket. See you on https://github.com/gratipay/gratipay.com/issues/3399!

**Comment by whit537** [comment]
[Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077)

**Comment by JanelleOrsi** [comment]
I haven't been following this conversation closely enough, but in case it's relevant, the CA Department of Business Oversight has opened a new comment period on a proposed amendment to the Money Transmission Act and comments are due June 4:  http://www.dbo.ca.gov/Licensees/money_transmitters/Regulations.asp

It's only worth commenting on if you think check sellers, bill payers, and proraters licensed under the Check Sellers, Bill Payers, and Proraters Law (Fin. Code, § 12000 et seq.) should be exempt from the Money Transmission Act. It certainly sounds like overkill to make them get licensed twice. But I haven't looked closely enough to see how check sellers, bill payers, and proraters are defined.
