### ISSUE TITLE
radar 5

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#195]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/191)

**Comment by whit537** [comment]
Here's what's on my radar this week, and why:

- [ ] Double-store payments info. External pressure because Balanced is shutting off their API in [38 days](https://daycalc.appspot.com/06/11/2015) and this is the next step on https://github.com/gratipay/gratipay.com/issues/3377.

- [ ] Keep other pieces of the migration plan moving forward (https://github.com/gratipay/gratipay.com/issues/3377). External pressure because not all parts of the plan are fully locked in yet.

**Comment by techtonik** [comment]
- [ ] create http://bost.ocks.org/mike/sankey/ for https://github.com/gratipay/gratipay.com/tree/master/data because I want clarity (#3326, #3319)

- [ ] read the docs about OAuth (#2854), because it constantly slips off my radar

**Comment by whit537** [comment]
@benhc123 I notice you've doubled your take for this week. Haven't heard from you in a while. What are you working on?

**Comment by benhc123** [comment]
@whit537, Only for one week. I'm paying for a book on Python so I can help more with the development side of things (Aspen).

**Comment by whit537** [comment]
@benhc123 Cool, thanks for the heads-up. Huzzah for Python! :D :snake:

**Comment by kaguillera** [comment]
I know this is a little late but I am looking at the following:
- [ ] Looking at (https://github.com/gratipay/gratipay.com/issues/3377) to see how I can assist if possible
- [ ] Looking at (https://github.com/gratipay/gratipay.com/issues/3331) also since the fix I attempted seem to not have worked
- [ ] Still working on (https://github.com/gratipay/gratipay.com/issues/3171) more specifically (https://github.com/gratipay/gratipay.com/issues/2534)

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/200)

**Comment by whit537** [comment]
![screen shot 2015-05-11 at 8 07 51 am](https://cloud.githubusercontent.com/assets/134455/7564458/db932d58-f7b4-11e4-877c-781bd89ed82d.png)
