### ISSUE TITLE
radar 6

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#200]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/195)

**Comment by whit537** [comment]
Wow. Seems to me like we skipped a radar scan in there, but that's just because last week was so momentous: we [stopped processing payments](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8) because of legal concerns with our old terms of service (#192). While dead, we pivoted (#180 ... yes, really :grinning:) to focus exclusively on Teams. This week, I'm working on bringing Gratipay back from the dead, because I want Gratipay to not be dead, because I love it. :)

My primary goal this week is to run payday on Thursday, even if Gratipay is the only Team, though I'm hopeful we'll have at least one or two others as well. There's a fair bit of work to do to pull that off, and of course we're in the middle of migrating to a [new processing infrastructure](https://github.com/gratipay/gratipay.com/issues/3377) as well. Should be an interesting week! :-)

For the pivot line of work, here's what we need:

 - [ ] Rewrite terms of service: https://github.com/gratipay/gratipay.com/issues/3390.
 - [ ] Implement an application and approval system: https://github.com/gratipay/gratipay.com/issues/3395.
 - [ ] Update payday to constrain based on approval: https://github.com/gratipay/gratipay.com/issues/3396.

For the processing infrastructure line of work, here's what this week holds:

 - [ ] Migrate cards to Braintree: https://github.com/gratipay/gratipay.com/issues/3391.
 - [ ] Start vaulting new cards at Braintree: https://github.com/gratipay/gratipay.com/pull/3389.
 - [ ] Meet with Citizens: https://github.com/gratipay/gratipay.com/issues/3366.
 - [ ] Change Braintree to settle to New Alliance temporarily, until we're online with Citizens: https://github.com/gratipay/gratipay.com/issues/3287#issuecomment-100375150.

We're not going to run on Braintree this week, because it's too tight for migrating cards and changing where we settle, especially with the pivot. Let's aim to can run cards on Braintree next week.

**Comment by rohitpaulk** [comment]
- [ ] https://github.com/gratipay/gratipay.com/pull/3389 (Start vaulting new cards at Braintree)
- [ ] https://github.com/gratipay/gratipay.com/pull/3400 (promote Teams to first class citizens)
- [ ] https://github.com/gratipay/gratipay.com/issues/3391 (Migrate cards to Braintree) when it's ready.

**Comment by techtonik** [comment]
I finish my experiments with LXD workflow (as a replacement to Docker and Vagrant) and I am almost ready to submit it to repository. I couldn't use Docker, because I am on 32-bit machine.

**Comment by whit537** [comment]
This seems as good a place as any to report financial updates:

 - I've arranged with @copiesofcopies to pay $2,500.00 per month for the next two months. At that point our situation will have settled down and we can reach a further agreement on payment going forward. I've update the [budget](http://inside.gratipay.com/appendices/finances).
 - I spent $32.50 on :beers: last night to celebrate our [return to processing] (https://github.com/gratipay/gratipay.com/issues/3415).

**Comment by whit537** [comment]
We currently have $949.98 in operations. I have two [personal consulting](https://whit537.org/consulting) invoices outstanding, the payments from which I'm planning to invest into Gratipay, LLC to cover Tor Ekeland for the next two months.

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/206)

**Comment by whit537** [comment]
![screen shot 2015-05-18 at 9 36 32 am](https://cloud.githubusercontent.com/assets/134455/7681848/71df5bc4-fd41-11e4-8500-d56d67a648a9.png)
