### ISSUE TITLE
Radar 7

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#206]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/200)

**Comment by whit537** [comment]
We did it! Thanks to hard work from @rohitpaulk and @copiesofcopies, and input and encouragement from many others, we started processing again as Gratipay 2.0 last week.

!m *

This week, I'm working to solidify and maybe even land the [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) milestone, because I don't want all our efforts last week to go to waste. Let's try to build momentum. We processed payments for six teams last week (Gratipay included). Can we bring that up to 12 this week?

 - [ ] Turn on subscriptions to Teams (https://github.com/gratipay/gratipay.com/issues/3432).
 - [ ] Bring back payroll (https://github.com/gratipay/gratipay.com/issues/3433).
 - [ ] Announce the changes (https://github.com/gratipay/gratipay.com/issues/3419).

I also have an eye on the [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown) milestone, because we've got a hard deadline in [25 days](https://daycalc.appspot.com/06/12/2015). Priorities this week:

 - [ ] Run on Braintree this Thursday (https://github.com/gratipay/gratipay.com/issues/3287).
 - [ ] Finalize our partnership with Citizens (https://github.com/gratipay/gratipay.com/issues/3366).
 - [ ] Sort out vaulting (https://github.com/gratipay/gratipay.com/issues/3388) and migration (https://github.com/gratipay/gratipay.com/issues/3379) of bank account and identity data.

This last point is entangled with the Pivot, because if we're *not* going to get bank account and identity info from Balanced, then it makes sense to ask people to give us that info again when they migrate their tips to to subscriptions, since we've already got their attention at that point.

**Comment by kaguillera** [comment]
Going to start working on a Team profile page for turning on the subscriptions (https://github.com/gratipay/gratipay.com/issues/3432).

**Comment by whit537** [comment]
@rohitpaulk I'm going to keep going with https://github.com/gratipay/gratipay.com/issues/3419 for a bit here this morning. Do you want to get a PR going for charging on Braintree?

**Comment by whit537** [comment]
Inbox 2! :dancer: With [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) I closed my two oldest emails threads! :dancer:

**Comment by whit537** [comment]
Support 1! Phew. O.o

**Comment by whit537** [comment]
Alright, I am mostly working for someone else today. I'll be checking in periodically, to keep support topped up especially. We should blast out another email notice like we did for the Gratipocalypse, but that can wait until early next week.

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/209)

**Comment by whit537** [comment]
![screen shot 2015-05-25 at 8 34 35 pm](https://cloud.githubusercontent.com/assets/134455/7803429/90dc2dfe-031d-11e5-9dd6-d2588554f012.png)
