### ISSUE TITLE
Radar 8

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#209]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/206)

**Comment by whit537** [comment]
This week I'm working on the [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) because I want to land it now that we're over the hump, and the [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown) because we have a hard deadline in [17 days](https://daycalc.appspot.com/06/11/2015).

For the Pivot I'm looking at three things:

 - [ ] Keeping up with support.
 - [ ] Bringing back payroll (https://github.com/gratipay/gratipay.com/issues/3433).
 - [ ] Bringing back account closing (https://github.com/gratipay/gratipay.com/issues/3461).

For the Balanced Shutdown I'm looking at three things:

 - [ ] Running on Braintree this Thursday (https://github.com/gratipay/gratipay.com/issues/3287).
 - [ ] Finalizing our partnership with Citizens (https://github.com/gratipay/gratipay.com/issues/3366).
 - [ ] Sorting out vaulting (https://github.com/gratipay/gratipay.com/issues/3388) and migration (https://github.com/gratipay/gratipay.com/issues/3379) of bank account and identity data.

This last point is entangled with the Pivot, because if we're *not* going to get bank account and identity info from Balanced, then it makes sense to ask people to give us that info again when they migrate their tips to subscriptions, since we've already got their attention at that point.

**Comment by whit537** [comment]
Today is a holiday. I'll be working a bit this morning (focusing on support, and documentation for Citizens), then I'll be out the rest of the day. I'm offline working elsewhere tomorrow, then back for full days on Wednesday and Thursday.

**Comment by whit537** [comment]
GitHub 1. I took a pass through support and bumped a number of folks down the road a couple days.

**Comment by techtonik** [comment]
* [ ] Getting my research about [using LXD for Gratipay](http://piratepad.net/gratipay) into official docs

**Comment by whit537** [comment]
!m @techtonik 

I'm working on getting documentation to Citizens (https://github.com/gratipay/gratipay.com/issues/3366) this morning, then I'll be taking another pass through support. I'd like to make progress on payroll and Braintree today, so that we can run with both tomorrow.

**Comment by whit537** [comment]
I'm looking at https://github.com/gratipay/gratipay.com/issues/3482 because I want to direct people to apply for teams but we're losing information. :-/

**Comment by whit537** [comment]
Took a pass through support. I'm blocking six on https://github.com/gratipay/gratipay.com/pull/3485.

**Comment by whit537** [comment]
Okay! Laundry/lunch and then coffeeshop to find @kaguillera. :)

**Comment by whit537** [comment]
Gonna land https://github.com/gratipay/gratipay.com/issues/3453 as we have several support requests related to that.

**Comment by whit537** [comment]
Alright, https://github.com/gratipay/gratipay.com/pull/3485 and https://github.com/gratipay/gratipay.com/pull/3453 are both done. Back to support ...

I have another ~3.5 hours today (and I'm at the coffee shop, so interruptible). @rohitpaulk What's your availability like in the next ~24 hrs? Any cycles available for gratipay/gratipay.com#3433 and/or gratipay/gratipay.com#3287?

**Comment by whit537** [comment]
Per IRL convo, @kaguillera is looking at https://github.com/gratipay/gratipay.com/issues/3479.

**Comment by whit537** [comment]
Inbox 1(!), GitHub 0, Support 15.

**Comment by rohitpaulk** [comment]
I've been busy this week, will be available tomorrow and day after. I'll get https://github.com/gratipay/gratipay.com/issues/3397 started tomorrow so that https://github.com/gratipay/gratipay.com/pull/3450 isn't blocked.

**Comment by whit537** [comment]
> I'll get gratipay/gratipay.com#3397 started tomorrow so that gratipay/gratipay.com#3450 isn't blocked.

Cool. If we're lucky we can include you and me on Gratipay's payroll tomorrow. :-)

I'll pick up with https://github.com/gratipay/gratipay.com/pull/3473 once I get caught up with support ...

**Comment by whit537** [comment]
> If we're lucky we can include you and me on Gratipay's payroll tomorrow. :-)

As well as @kaguillera @techtonik and any other team members who are paying attention ...

**Comment by whit537** [comment]
Alright! Made it through support. Support 9. Inbox 1, GitHub 0. Will look at gratipay/gratipay.com#3473 tomorrow morning ...

**Comment by whit537** [comment]
!m *

**Comment by techtonik** [comment]
@whit537, are the legal requirements to get on the payroll explained anywhere? I'd like to avoid using "privileged channel" and try to catch the user experience of an ordinary GP visitor.

**Comment by whit537** [comment]
Support 15

**Comment by whit537** [comment]
Alright, Support 6, close enough. Inbox 1, GitHub 0.

**Comment by whit537** [comment]
Turning to https://github.com/gratipay/gratipay.com/issues/3486 ...

**Comment by whit537** [comment]
> the legal requirements to get on the payroll explained anywhere

No, not really.

> the user experience of an ordinary GP visitor.

At this point we're trying to get payroll run barely at all once, just for the Gratipay team this week with a couple of us as members, and that if we're lucky. We'll revisit general user experience down the line.

**Comment by whit537** [comment]
Wow. Made it onto Braintree! O.o

!m @rohitpaulk 

I'm consulting today, will be checking in periodically, hoping to take a final sweep through support this afternoon. Next week: payroll!

**Comment by whit537** [comment]
Okay, back for a couple hours. I want to take a pass through support and get an email blast out about Gratipay 2.0 (https://github.com/gratipay/gratipay.com/issues/3419). I also need to communicate something to Citizens about #119.

**Comment by whit537** [comment]
I just invested $2,000 into Gratipay, LLC, so that we can meet our $2,500 obligation to Tor Ekeland next week.

**Comment by whit537** [comment]
I'm here to work on https://github.com/gratipay/inside.gratipay.com/issues/119. I think we need to pull off https://github.com/gratipay/gratipay.com/issues/3289 in order to make it through Citizens underwriting.

**Comment by whit537** [comment]
Turning to the AML section of the FinCEN [manual](http://www.fincen.gov/news_room/rp/files/MSB_Exam_Manual.pdf) ...

**Comment by whit537** [comment]
You know what? Gratipay 2.0 is actually not that dissimilar from ~~oDesk~~ [Upwork](https://www.upwork.com/blog/2015/05/odesk-is-now-upwork/).

**Comment by whit537** [comment]
Dialed back out of the #119 rabbit-hole, summary of findings at https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-107299924.

:swimmer:

**Comment by whit537** [comment]
Happy 3rd Birthday, Gratipay! :dancer: :birthday: :balloon: :confetti_ball:

**Comment by whit537** [comment]
First task today is to update [Manage Risk](http://inside.gratipay.com/howto/manage-risk) with everything else I learned over the weekend, and deliver that to Citizens.

After that, I intend to:

 - [ ] write a little blog post about our birthday
 - [ ] send out a birthday email blast re: Gratipay 2.0
 - [ ] take a pass through support
 - [ ] dive in on https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-107299924 :swimmer:

**Comment by whit537** [comment]
Oh, gosh! It's Monday ... :)

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/224)

**Comment by whit537** [comment]
![screen shot 2015-06-01 at 2 21 14 pm](https://cloud.githubusercontent.com/assets/134455/7919931/80cdbc88-0869-11e5-8f17-9ca90b27ee3b.png)
