### ISSUE TITLE
Radar 9

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#224]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/209)

**Comment by whit537** [comment]
Happy 3rd Birthday, Gratipay! :dancer: :birthday: :balloon: :confetti_ball:

**Comment by whit537** [comment]
I'm taking my eyes off the [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) cleanup this week, to focus on the [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown). Our objective is to run ACH on Citizens on June 18. Here's the short version of [what that entails](https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-107299924):

 - [ ] strengthen our infosec (#223)
 - [ ] clear Balanced underwriting (gratipay/gratipay.com#3379)
 - [ ] migrate data

----

 - [ ] strengthen our AML (#119)
 - [ ] clear Citizens underwriting (gratipay/gratipay.com#3366)
 - [ ] implement Citizens

----

 - [ ] run on Citizens

We need to strengthen our infosec before we can strengthen our AML or implement Citizens, because strengthening our AML involves collecting and storing more personally identifying information (PII), and implementing Citizens involves collecting and storing bank account numbers: we need to be able to handle that sensitive information securely before we start doing so. Therefore, I expect to spend most of my time on infosec this week, though we'll also need to get the conversation going with Citizens underwriting.

**Comment by whit537** [comment]
My first task today is to update [Manage Risk](http://inside.gratipay.com/howto/manage-risk) with everything else I learned over the weekend, and deliver that to Citizens. After that, I intend to:

 - [ ] write a little blog post about our birthday
 - [ ] send out a birthday email blast re: Gratipay 2.0
 - [ ] take a pass through support
 - [ ] dive in on #223 :swimmer:

**Comment by whit537** [comment]
Got the bill from @copiesofcopies, it came to $7,853.95. Our agreement is $2,500 per month. Our Chase QuickPay daily limit is $2,000, so I paid that much today and will follow up Wednesday with another $500 (I'm offline tomorrow).

!m @copiesofcopies

**Comment by whit537** [comment]
Alright, [Manage Risk](http://inside.gratipay.com/howto/manage-risk) delivered in https://github.com/gratipay/gratipay.com/issues/3366#issuecomment-107643761.

**Comment by whit537** [comment]
Lunch 0, Inbox 0, GitHub 0, Support ... 35

**Comment by whit537** [comment]
Picked off low-hanging fruit and checked the spam queue. Support 18.

I'm gonna write a quick birthday blog post and then work on getting out an email.

**Comment by whit537** [comment]
[Gratipay, Year Three](https://medium.com/gratipay-blog/gratipay-year-three-73b5ba84c32d)

**Comment by whit537** [comment]
Alright, let's get that out in email ...

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/issues/3419 is the email blast ticket.

**Comment by whit537** [comment]
Email out. https://github.com/gratipay/gratipay.com/issues/3419 closed.

**Comment by whit537** [comment]
Support 18.

**Comment by whit537** [comment]
Support 1! :dancer:

**Comment by whit537** [comment]
Support 2.

**Comment by whit537** [comment]
Support 1.

**Comment by whit537** [comment]
Okay! Diving in on #223 ...

**Comment by whit537** [comment]
Support 1.

I'm looking at #214 ahead of 10am call. I've also got a 9am Aspen call with @pjz, and an 11:30am call with Citizens (gratipay/gratipay.com#3366).

**Comment by techtonik** [comment]
* [ ] waiting for 0.5.2 of https://www.npmjs.com/package/grunt-webdriver to be released for the next round of deal with our jstests competence/technical debt
* [ ] LXC/LXD is also stalled due to https://github.com/lxc/lxd/issues/714 - I don't know how the mapping mechanism in containers should work

Also, with all these new abbreviations and stuff GP starts to feel very obscure and complicated. I think it is critical to simplify things as much as possible to keep trust of people in the service. Even though we are all legal and correct, the interest of users is to have a clean and transparent service, not the one that is forced to be obscure by following the years of some professional practice in legal and financial world.

**Comment by whit537** [comment]
>[W]ith all these new abbreviations and stuff GP starts to feel very obscure and complicated.

@techtonik I agree. Want to put together a glossary for IG? :)

**Comment by kaguillera** [comment]
+1 for glossary

**Comment by whit537** [comment]
I dropped us back from three to two full-time agents on Freshdesk, saves us $19/mo.

**Comment by whit537** [comment]
I made the second payment of $500 to Tor Ekeland.

**Comment by techtonik** [comment]
New goal:

* [ ] Waiting for https://github.com/gratipay/gratipay.com/pull/3524 to be merged to fix https://github.com/gratipay/gratipay.com/issues/3000 and switch to https://github.com/gratipay/gratipay.com/issues/3069

Where to put the glossary? On gratipay.com or on inside.gratipay.com?

**Comment by whit537** [comment]
> Where to put the glossary? On gratipay.com or on inside.gratipay.com?

@techtonik I would think: http://inside.gratipay.com/appendices/glossary

**Comment by whit537** [comment]
Contracting today. I'll be around for the call with Zipmark in an hour (https://github.com/gratipay/gratipay.com/issues/3491#issuecomment-109074174).

**Comment by whit537** [comment]
Milestones have been helpful for the Pivot and the Balanced Shutdown. As we start to emerge from and look beyond those events, I've made two new milestones, one for AML Program and another for Payroll.

https://github.com/gratipay/gratipay.com/milestones/AML%20Program
https://github.com/gratipay/inside.gratipay.com/milestones/AML%20Program

https://github.com/gratipay/gratipay.com/milestones/Payroll
https://github.com/gratipay/inside.gratipay.com/milestones/Payroll

**Comment by whit537** [comment]
[next week](https://github.com/gratipay/inside.gratipay.com/issues/244)

**Comment by whit537** [comment]
![screen shot 2015-06-08 at 9 24 39 am](https://cloud.githubusercontent.com/assets/134455/8035635/393be30c-0dc0-11e5-8e73-66de8f56114d.png)
