### ISSUE TITLE
Radar 24

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#343]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/332)

**Comment by whit537** [comment]
#### Roadmap ([what?](http://inside.gratipay.com/howto/sweep-the-radar))


###### Next Three Weeks

 - Week 24—September 13—[Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown), with a focus on [double-entry accounting](https://github.com/gratipay/gratipay.com/pull/3653)
 - Week 25—September 20—[Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown), focus on cleaning up history ([e.g.](https://github.com/gratipay/gratipay.com/issues/2779)); meeting with CPA is Sept 23
 - Week 26—September 27—final push on [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown); [refund 1.0 money](https://github.com/gratipay/gratipay.com/issues/3539)!

###### Longer Term

[![roadmap](https://cloud.githubusercontent.com/assets/134455/9171649/6a838b2a-3f3b-11e5-8cbb-bf5efbab50b9.png)](http://interactive.blockdiag.com/?compression=deflate&src=eJyFU01vnDAQvfMrRvTaRrQ5RShdbUlTRUqkqES5dHuYNbOstcZGYNiiaP97x4Y1qJG6nDxvPvze87BVRhwKiSW8RbBTXbuHXwq3pG7jex99vkrgyWga4o8gjDLNbfzhnr8si39HEXzh9LnhWfbGLsqS5Po6SRiw9MeO4HEvLbk-a0PbC2EFL3iglidC2Ziuhrd5xs0Nz4jA3_TpK8QZij0V8Iqq445Fws_5Sb2k4xImK64Wsdc4h9ZGcGI-JWIdGP1Yr5-DjoaK9woggoJaWerQc-fDi121kLNf2QPc5fnFHqpmat-rWpmhIm3hEY__b41g22Lo_JavL5V3-hDKV6vVJWLvHsttBe9F6t1MJ4dSpzl1IlLHJ3W3nMYNYP8ZHk3hs9Q705IYBXNc49AYpabHmd_OqeJo_fQ4UuZzhpjzzGlCEPHAcU7C7ZUs-hku2D9ph41-pUbupEArjXZV05XzE42xH6B7I4XU5WL6hLg0swkJPk_DTGfbAG9RHzZ6Ql2BYx2ymalq1ANgu9EIOTW9FOT_sX9czjL_9_EOn-U671iet3Ci5LIjFFw8A47piDseM-495J_h9BdebEl5)

**Comment by whit537** [comment]
#### Queues ([what?](http://inside.gratipay.com/howto/manage-queues))

| Open | Closed | Queue | Description |
|---:|---:|:---|:----|
| 0 | 23 | [Violations](https://github.com/gratipay/safety/issues) | [private communication amongst the safety team](http://inside.gratipay.com/howto/handle-terms-violations) |
| 9 | 12 | [Security](https://hackerone.com/bugs?team_id=1868) | [private communication with security researchers](http://inside.gratipay.com/howto/handle-security-issues) |
| 5 | 25 | [Legal](https://github.com/gratipay/legal/issues) | private communication with our counsel |
| 0 | 892 | [Support](https://gratipay.freshdesk.com/helpdesk/tickets/view/1000240520) | [private communication with users](http://inside.gratipay.com/howto/support-users) |
| 0 | 107 | [L2 Support](https://gratipay.freshdesk.com/helpdesk/tickets/view/1000241179) | [escalated support issues](http://inside.gratipay.com/howto/support-users) |
| 11 | 49 | [Team Review](https://github.com/gratipay/applications/issues) | public review of applications for new [teams](https://gratipay.com/explore/teams/) |
| ? | ? |  [Errors](https://beta.getsentry.com/gratipay/gratipay-com/?sort=freq&df=&tt=&tf=&dt=&date_type=last_seen&cursor=0:110:0) | production errors |
| 0 | 1,684 | [Vendors, etc.](https://gratipay.freshdesk.com/helpdesk/tickets/view/1000240519) | private communication with our vendors<br>(*also includes low-volume mailboxes:* safety *and* security) |
| 21 | 113 | [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) | a milestone | 
| 16 | 44 | [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown) | a milestone | 
| 7 | 9 | [Milestones](https://github.com/gratipay/gratipay.com/milestones) | all milestones |
| 5 | 509 | [PR Review](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+label%3AReview) | work in the final stage before deployment |
| 22 | 1,652 | [PRs](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+user%3Agratipay+) |  all work in progress |
| 768 | 4,420 | [Issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay+) | public communication with [contributors](http://inside.gratipay.com/big-picture/welcome) |

**Comment by kzisme** [comment]
Twitter, and random issues I see that I can tackle.  Also still getting used to my new machine.  I hope to be able to contribute more soon :smile: 

If you do find anything to post to Twitter ping me!

**Comment by whit537** [comment]
Well, we're outta time to work on the [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot), if we're going to get the work done we want before the [Balanced Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown). I'm switching gears to that.

Another new thing since last week: our competition with Bountysource (#316) has come to a head. @kzisme Can you work with these two links on Twitter this week?

 - http://gratipay-or-bountysource.guide/
 - https://github.com/gratipay/inside.gratipay.com/issues/316

Bountysource puts pressure on us to deliver on product, and [Balance Shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20Shutdown) does not really help in terms of user-facing changes. [Pivot](https://github.com/gratipay/gratipay.com/milestones/Pivot) is about user-facing changes, but they're nothing flashy. Could something like https://github.com/gratipay/gratipay.com/issues/5 be a quick win for us vis-à-vis Bountysource? Should we fast-track something like that to stay competitive in the short term?

Not that I have time, if we're to be ready for me to meet with the CPA next week. :-/

**Comment by techtonik** [comment]
* [ ] I want to merge pure Python SASS - https://github.com/gratipay/inside.gratipay.com/pull/340 - looks like compiling SASS templates is a one-time operation, so we may switch to it for gratipay.com as well. This will allow me to experiment with styles in familiar environment

Then there are again, a couple of issues with Aspen
* [ ] https://github.com/gratipay/aspen.py/issues/513 - errors on http://aspen.io/
* [ ] https://github.com/gratipay/inside.gratipay.com/issues/341 - local copy of http://inside.gratipay.com/ is unable to load SVG images

I've got some progress speaking with lawyers about how to receive money from Belarus. Now I just need a lot of time to validate all information and make a write up on that.

**Comment by whit537** [comment]
@kzisme Another post for Twitter?

http://coffeeonthekeyboard.com/bounties-and-tips-1204/

**Comment by kzisme** [comment]
@whit537 I'm going to reach out to a few FOSS org's this week and see if they know about Gratipay and such (and direct them towards out blog).  

Any suggestions on how to not sound like a sales-person?

**Comment by whit537** [comment]
@kzisme This is from Twitter, you mean? I would say definitely don't cold-tweet *personal* Twitter accounts. I think if you're communicating with project accounts it's probably okay. Also consider linking to https://gratipay.com/about/.

**Comment by whit537** [comment]
@kzisme What do you think about http://gratipay-or-bountysource.guide/ for Twitter?

**Comment by kzisme** [comment]
Yeah, those are for Twitter.  

When speaking to other people ie: Openhatch how should I introduce the idea?  

I like http://gratipay-or-bountysource.guide/  - but my only concern is that some people may not even be aware of the launch of Salt, so we may be doing more harm than good.

This is not to say that it can't be used or a great resource, but I think timing is important.

**Comment by whit537** [comment]
> This is not to say that it can't be used or a great resource, but I think timing is important.

Okay, your call. :-)

> When speaking to other people ie: Openhatch how should I introduce the idea?

Maybe something like "Would you consider applying for Gratipay?" Remember that we can't promise anything, they still have to go through Team review.

**Comment by kzisme** [comment]
I'll see what I can do and keep you posted :)

**Comment by whit537** [comment]
!m @kzisme

**Comment by mattbk** [comment]
> Could something like gratipay/gratipay.com#5 be a quick win for us vis-à-vis Bountysource? Should we fast-track something like that to stay competitive in the short term?

Wish I had the time to learn this week.  There's an $80 bounty on that one!  Maybe I'm better off chipping $10 more into that...

Support is still 0 for now.

**Comment by kzisme** [comment]
@whit537 @mattbk How do bounties work?  I have a general idea, but what has to be done to receive payment?

**Comment by whit537** [comment]
Noting the irony ... https://github.com/gratipay/inside.gratipay.com/issues/116. :-)

**Comment by mattbk** [comment]
For Twitter, could keep reminding people that direct contributions help a direct economy that isn't ad-based:

**Comment by mattbk** [comment]
http://www.theawl.com/2015/09/welcome-to-the-block-party

**Comment by mattbk** [comment]
Does AdBlock fit with Gratipay's values? https://getadblock.com/installed/?u=sfcjbyt778748123

**Comment by whit537** [comment]
It does unless someone wants to make a case that it doesn't. ;-)

**Comment by whit537** [comment]
And, of course, they'd have to apply first! :dancer: 

I started getting my head back into https://github.com/gratipay/gratipay.com/pull/3653 yesterday, the accounting refactor. I salvaged an orthogonal commit from there and made a PR, https://github.com/gratipay/gratipay.com/pull/3785, and started thinking about what to do with the rest.

I'm starting over on that work, reframing it in terms of the dashboard, which is currently moribund (we no longer use it for Team review after https://github.com/gratipay/gratipay.com/pull/3484, and we don't really review ~users anymore (though we should double-check the implications of that—are we not charging some people that we should be?). What I want to show the accountant next week is an accounting application, a general ledger and chart of accounts. This will become the new heart of Gratipay as an application, and I'm approaching this in terms of writing an accounting web app to be parked at `/dashboard`. I evaluated [JavaScript frameworks](https://www.google.com/trends/explore#q=angular%20js%2C%20react%20js%2C%20ember%20js%2C%20backbone%20js&cmpt=q&tz=Etc%2FGMT%2B4) yesterday. I couldn't get Angular's hello world to run(?!), and am settling on Backbone (fits my brain the best). I'm afk today but will resume tomorrow, hopefully starting a new PR.

!m *

**Comment by mattbk** [comment]
Yes, they'd have to apply, and they'd have to be open.  I think they're pretty open: http://support.getadblock.com/kb/about-the-project/how-can-i-support-adblock

**Comment by kzisme** [comment]
@whit537 One tweet posted.  I'm trying ~not~ to attack Bountysource - but promote openness and open work.  Let me know what you think: https://twitter.com/Gratipay/status/643853044187299840

**Comment by kzisme** [comment]
@whit537 Also would it be beneficial to post on HN in the coming weeks about Gratipay 2.0 and payouts and such?  I feel it would be.

**Comment by tshepang** [comment]
It still comes off to me as an attack. I would be more happy with something as boring as "Some comparison with our closest competitor".

**Comment by kzisme** [comment]
@tshepang Tweet removed and re-tweeted a revised version.  Thanks for the feedback!

**Comment by kzisme** [comment]
Also after reading through http://coffeeonthekeyboard.com/bounties-and-tips-1204/ it does seem that most users looking at Gratipay ~are~ interested in a one-off donation sometimes.  

Just some food for thought :hamburger:

**Comment by whit537** [comment]
Here's a dozen projects that should know about Gratipay:

http://us5.campaign-archive2.com/?u=744876426414b018c030e670a&id=0ff3704aaa

**Comment by whit537** [comment]
> Also would it be beneficial to post on HN in the coming weeks about Gratipay 2.0 and payouts and such? I feel it would be.

Yeah, probably. I say go for it! :-)

> It still comes off to me as an attack.

It's *supposed* to be an attack, predicated on the idea that we're competing with Bountysource (#316). If we're *not* competing with them (https://github.com/gratipay/inside.gratipay.com/issues/316#issuecomment-140174775) then I think we should just talk about other stuff on Twitter.

Also, @kzisme: https://gratipay.com/~kaytrance/ is false. That's a link to a ~user account, and the ~user doesn't have a Team.

**Comment by whit537** [comment]
Sorry, I meant https://twitter.com/typwrittr/status/602717349754568704 is false.

**Comment by kzisme** [comment]
Will remove when I get home. I've been searching for people who tweeted
about us in the past.

**Comment by whit537** [comment]
Let's not https://gratipay.com/dashboard/1.0-payouts before payday this week.

**Comment by tshepang** [comment]
I see no need to attack competitors. Am I missing something here? Why attack? You can still talk about how Gratipay is better without attacking (unless we are here having different definitions for the same word).

**Comment by whit537** [comment]
@tshepang Yes, let's drop the martial language, sorry. I mean, "Engage in direct competition."

**Comment by kzisme** [comment]
Most recent [Twitter](https://twitter.com/Gratipay/status/644244574165012480) post.

**Comment by whit537** [comment]
!m @kzisme

**Comment by mattbk** [comment]
> Let's not forget https://gratipay.com/dashboard/1.0-payouts before payday this week.

To be approved, they have to be open-work people, right?

**Comment by whit537** [comment]
@mattbk No. For individual payouts the only criteria is that they provided some product or service (no "give me money for no reason at all"). It doesn't have to have been open work. You up for tackling that queue?

**Comment by mattbk** [comment]
Okay, that's much clearer, thanks.  I'm going through some of them now.

**Comment by whit537** [comment]
!m @mattbk

**Comment by whit537** [comment]
I'm working on https://github.com/gratipay/gratipay.com/pull/3786. I've stumbled upon a nice pattern for improving our API and our software documentation at the same time. :-)

**Comment by mattbk** [comment]
Majority are explicitly doing work.  Others had already deleted their profile description, but from github pages and others they are involved in various projects that are work.

**Comment by whit537** [comment]
Cool. That's about what I've been expecting.

**Comment by kzisme** [comment]
Newest [Twitter](https://twitter.com/Gratipay/status/644557580178731009) post.

**Comment by mattbk** [comment]
You could also chime in with this conversation, if you want: https://twitter.com/untitaker/status/644525326098395136

**Comment by kzisme** [comment]
Will do 

!m @mattbk

**Comment by mattbk** [comment]
Building forms (e.g., https://github.com/gratipay/gratipay.com/issues/3767) is interesting to me, but I'm not sure I understand how to build and then do the database I/O in Python/Gratipay specifically.  Are there any resources out there about this?

**Comment by whit537** [comment]
@mattbk Best bet is to start with existing code that is close to what you want, and work from those examples. My hope and dream is the docs I've got going on https://github.com/gratipay/gratipay.com/pull/3786#issuecomment-141217331 can evolve into what you need.

**Comment by whit537** [comment]
Alright, hitting pause on https://github.com/gratipay/gratipay.com/pull/3786 in order to run payday: https://github.com/gratipay/inside.gratipay.com/issues/344.

**Comment by kzisme** [comment]
Before replying to this Tweet....We don't have any plans to move from PayPal?  I had an inquiry reguarding us moving away from Paypal to avoid fees.

I'm not aware of us moving away from that current model, but just wanted to check.    

https://twitter.com/failvarez/status/644672998088163328

**Comment by mattbk** [comment]
The hope is to get bank transfers back with [something like Dwolla](https://github.com/gratipay/gratipay.com/issues/726) (not sure of status of that issue, @whit537).  Right now you can't apply without a payout route, and the only payout route we have right now is PayPal.

**Comment by whit537** [comment]
#### Email ([what?](http://inside.gratipay.com/howto/sweep-the-radar))

![screen shot 2015-09-22 at 10 03 27 am](https://cloud.githubusercontent.com/assets/134455/10020496/3ca17f3a-6111-11e5-96b3-232b3e27fbf1.png)
