### ISSUE TITLE
Radar 32

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#395]
What are you working on this week and why?

[last week](https://github.com/gratipay/inside.gratipay.com/issues/389)

**Comment by whit537** [comment]
#### Roadmap ([what?](http://inside.gratipay.com/howto/sweep-the-radar))

###### Short Term

[Embarrassments](https://github.com/gratipay/inside.gratipay.com/issues/368#issuecomment-148587948):

 - can't edit teams ([Team Basics](https://github.com/gratipay/gratipay.com/milestones/Team%20Basics))
 - not using immutable ids (https://github.com/gratipay/gratipay.com/issues/835)
 - widgets are broken (https://github.com/gratipay/inside.gratipay.com/issues/389#issuecomment-153884921)
 - escrow imprecision (https://github.com/gratipay/inside.gratipay.com/issues/389#issuecomment-153929881)
 - Security 9 (https://github.com/gratipay/inside.gratipay.com/issues/389#issuecomment-153930768)

###### Long Term

[![roadmap](https://cloud.githubusercontent.com/assets/134455/9171649/6a838b2a-3f3b-11e5-8cbb-bf5efbab50b9.png)](http://interactive.blockdiag.com/?compression=deflate&src=eJyFU01vnDAQvfMrRvTaRrQ5RShdbUlTRUqkqES5dHuYNbOstcZGYNiiaP97x4Y1qJG6nDxvPvze87BVRhwKiSW8RbBTXbuHXwq3pG7jex99vkrgyWga4o8gjDLNbfzhnr8si39HEXzh9LnhWfbGLsqS5Po6SRiw9MeO4HEvLbk-a0PbC2EFL3iglidC2Ziuhrd5xs0Nz4jA3_TpK8QZij0V8Iqq445Fws_5Sb2k4xImK64Wsdc4h9ZGcGI-JWIdGP1Yr5-DjoaK9woggoJaWerQc-fDi121kLNf2QPc5fnFHqpmat-rWpmhIm3hEY__b41g22Lo_JavL5V3-hDKV6vVJWLvHsttBe9F6t1MJ4dSpzl1IlLHJ3W3nMYNYP8ZHk3hs9Q705IYBXNc49AYpabHmd_OqeJo_fQ4UuZzhpjzzGlCEPHAcU7C7ZUs-hku2D9ph41-pUbupEArjXZV05XzE42xH6B7I4XU5WL6hLg0swkJPk_DTGfbAG9RHzZ6Ql2BYx2ymalq1ANgu9EIOTW9FOT_sX9czjL_9_EOn-U671iet3Ci5LIjFFw8A47piDseM-495J_h9BdebEl5)

**Comment by kzisme** [comment]
Twitter stuff as far as I know - there area a few upcoming events that are going to be posted (same as last week.)

Are there any features or things that need fixed that I can work on with someone?

**Comment by techtonik** [comment]
I am on my way to document Widgets process - https://github.com/gratipay/grtp.co/issues/107

Now I see that I need to also document how the Widgets actually work. Because they are actually clients for the Gratipay API, which is broken for individuals.

So, which kind of information do we need to provide from widget:

  * [ ] How much I as an individual contribute on Gratipay (from all teams)?
  * [ ] How much I as an individual receive on Gratipay (from all teams)?
  * [ ] How my team receives on Gratipay?
  * [ ] How my team gives on Gratipay (it this at all possible)?

**Comment by whit537** [comment]
O.O

https://github.com/sharetribe/sharetribe

**Comment by whit537** [comment]
I'm pretty excited about Platform Cooperativism (#384) this weekend.

**Comment by mattbk** [comment]
Check out tonight's Daily Show interview with Dan Price. Says some cool things about love changing and creating economies.

**Comment by whit537** [comment]
!m Dan Price

**Comment by whit537** [comment]
http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/abdrbv/exclusive-dan-price-extended-interview

**Comment by tshepang** [comment]
not viewable here in South Africa :(

**Comment by mattbk** [comment]
That's relatively ironic.

**Comment by tshepang** [comment]
indeed

**Comment by whit537** [comment]
Ooh! http://pycaribbean.com/ Waddya say, @chrisdev @kaguillera? :dancer:

**Comment by chrisdev** [comment]
:+1: for me.

**Comment by whit537** [comment]
Flights are $500+. :-(

**Comment by chrisdev** [comment]
Yep.  Also in Feb so you can escape from old man winter

**Comment by whit537** [comment]
@chrisdev That means I would need *two* tickets. ;-)

**Comment by chrisdev** [comment]
Definitely so :smile:

**Comment by whit537** [comment]
I've been chipping away on https://github.com/gratipay/aspen.py/pull/527 so we can be more accessible to new developers ("We use Flask" is easier to say than "We use Aspen"). I'm pausing that to work on https://github.com/gratipay/inside.gratipay.com/pull/390 with @kaguillera this afternoon.

**Comment by mattbk** [comment]
Support 1.

Had a whirlwind vet trip to a different city Monday through today, so I'm a little scatterbrained.  Are there other simple tasks I can help with when not doing support?

**Comment by whit537** [comment]
!m @mattbk 

> Are there other simple tasks I can help with when not doing support?

Maybe go through the [ticket backlog](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Agratipay) and close or comment on any that are ready for it?

**Comment by whit537** [comment]
Picking up from https://github.com/gratipay/inside.gratipay.com/issues/384#issuecomment-155829205 ...

From: Neal

> Sure Chad, let's do it.

:dancer: 

To: Neal

>Awesome, thanks! :D
>
>Any of these times work for you?
>
Thursday, November 19 at 11am (California time, yes?)
Wednesday, November 25 at 11am
Wednesday, December 2 at 11am
>
Also: Anyone come to mind that you'd recommend I connect with this weekend? Anyone representing Shareable?
>
Thanks! :-)

**Comment by whit537** [comment]
Okay! Inbox 5, GitHub 0, Payday 0, Team Review 14, L2 Support 0, Vendors, etc. 0.

Platform Cooperative 1. :dancer:

Here I go! #384 :night_with_stars: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; :bus:

P.S. Not taking my 'top, so call/text if you need me: 1-412-925-4220.

!m *

**Comment by mattbk** [comment]
Support 0 to start off the week.

**Comment by mattbk** [comment]
Flexget included a link to a great blog post about contributing without being a coder: http://blog.smartbear.com/programming/14-ways-to-contribute-to-open-source-without-being-a-programming-genius-or-a-rock-star/

**Comment by whit537** [comment]
#### Email ([what?](http://inside.gratipay.com/howto/sweep-the-radar))

![screen shot 2015-11-17 at 10 08 52 am](https://cloud.githubusercontent.com/assets/134455/11215250/420291d4-8d13-11e5-8aa4-255c54c9efea.png)

**Comment by whit537** [comment]
Ooh! We're arbitrarily excellent again! Last week too, it looks like. :-)
