### ISSUE TITLE
reconcile June 2012

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#449]
The books for our first month are such chaos that I'm making a new ticket to work it through. Ready for the rabbit hole? :rabbit: :hamburger: 

#### To-do

 - [x] account for IHAM charges
 - [x] account for $3.66 Samurai discrepancy
 - [x] account for money in transit

**Comment by whit537** [comment]
Reticketed from #390.

**Comment by whit537** [comment]
On this w/ @kaguillera ... go! :horse_racing:

**Comment by whit537** [comment]
Looking at New Alliance, we have 11 transactions to account for:

```
6/28/2012			EFT DEP - STRIPE MERCHANT	$20.97	$130.41	
6/25/2012			EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/22/2012			EFT DEP - STRIPE MERCHANT	$0.22	$106.45	Samurai -> Stripe
6/18/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$2.01	$106.23	samurai by feefighters
6/18/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$2.92	$104.22	samurai by feefighters
6/11/2012			EFT W/D - MERCHANT BANKCD FEE	-$2.00	$101.30	samurai by feefighters
6/11/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$24.11	$103.30	samurai by feefighters
6/11/2012			EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012			EFT W/D - MERCHANT BANKCD FEE	-$31.35	$78.58	samurai by feefighters
6/4/2012			EFT W/D - MERCHANT BANKCD INTERCHNG	-$0.08	$109.93	samurai by feefighters
6/4/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$7.56	$110.01	samurai by feefighters

**Comment by whit537** [comment]
The goal here is to tease out which money is for what, and reconcile the Gittip money against our database. In Xero. The result of this ticket should be financial statements for #390 (income statement, balance sheet, transactions) for the month of June, 2012.

**Comment by whit537** [comment]
Here are the exchanges we have in the database for June 1:

```
=> select * from exchanges where timestamp > '2012-06-01'::timestamptz and timestamp < '2012-06-7'::timestamptz;
┌────┬───────────────────────────────┬────────┬──────┬─────────────┬──────────┬──────┬────────┬───────┬─────┐
│ id │           timestamp           │ amount │ fee  │ participant │ recorder │ note │ status │ route │ ref │
├────┼───────────────────────────────┼────────┼──────┼─────────────┼──────────┼──────┼────────┼───────┼─────┤
│  5 │ 2012-06-01 07:16:30.953249+00 │   0.99 │ 0.15 │ lgtest      │ ¤        │ ¤    │ ¤      │     ¤ │ ¤   │
│  4 │ 2012-06-01 07:16:28.443376+00 │   1.97 │ 0.19 │ whit537     │ ¤        │ ¤    │ ¤      │     ¤ │ ¤   │
└────┴───────────────────────────────┴────────┴──────┴─────────────┴──────────┴──────┴────────┴───────┴─────┘
(2 rows)

=> select sum(amount + fee) from exchanges where timestamp > '2012-06-01'::timestamptz and timestamp < '2012-06-7'::timestamptz;
┌──────┐
│ sum  │
├──────┤
│ 3.30 │
└──────┘
(1 row)
```

**Comment by whit537** [comment]
The fees to Samurai we know what to do with (more or less). Let's factor those out and look at just the income:

```
6/28/2012			EFT DEP - STRIPE MERCHANT	$20.97	$130.41	
6/25/2012			EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/22/2012			EFT DEP - STRIPE MERCHANT	$0.22	$106.45	Samurai -> Stripe
6/18/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$2.01	$106.23	samurai by feefighters
6/18/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$2.92	$104.22	samurai by feefighters
6/11/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$24.11	$103.30	samurai by feefighters
6/11/2012			EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012			EFT DEP - MERCHANT BANKCD DEPOSIT	$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
```
6/28/2012	EFT DEP - STRIPE MERCHANT				$20.97	$130.41	
6/25/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/22/2012	EFT DEP - STRIPE MERCHANT				$0.22	$106.45	Samurai -> Stripe
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.01	$106.23	samurai by feefighters
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.92	$104.22	samurai by feefighters
6/11/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$24.11	$103.30	samurai by feefighters
6/11/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
Our goal now is to reconcile the exchanges in the Gratipay database with the income stated above for New Alliance.

**Comment by whit537** [comment]
```sql
=> select date_trunc('day', timestamp) as day, sum(amount + fee) from exchanges where timestamp > '2012-05-31'::timestamptz and timestamp < '2012-07-01'::timestamptz group by day;
┌────────────────────────┬────────┐
│          day           │  sum   │
├────────────────────────┼────────┤
│ 2012-06-15 00:00:00+00 │   0.55 │
│ 2012-06-22 00:00:00+00 │  25.29 │
│ 2012-06-01 00:00:00+00 │   3.30 │
│ 2012-06-29 00:00:00+00 │ 111.00 │
│ 2012-06-08 00:00:00+00 │  25.28 │
└────────────────────────┴────────┘
(5 rows)
```

**Comment by whit537** [comment]
The $111 on the 29th doesn't hit New Alliance until the following month. We'll need to be able to account for that with an "in transit" or "pending" account in Xero in order to reconcile with both the Gratipay database and third parties (bank, processors) each month.

**Comment by whit537** [comment]
Here are the sums we need to reconcile with our bank statement:

```
│ 2012-06-01 │   3.30 │
│ 2012-06-08 │  25.28 │
│ 2012-06-15 │   0.55 │
│ 2012-06-22 │  25.29 │
```

**Comment by whit537** [comment]
Let's get the first payout out of there:

```sql
=> select date_trunc('day', timestamp)::date as day, sum(amount + fee), sum(fee) from exchanges where timestamp > '2012-05-31'::timestamptz and timestamp < '2012-07-01'::timestamptz and amount > 0 group by day order by day;
┌────────────┬────────┬───────┐
│    day     │  sum   │  sum  │
├────────────┼────────┼───────┤
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
│ 2012-06-22 │  25.29 │  4.62 │
│ 2012-06-29 │ 111.00 │ 15.76 │
└────────────┴────────┴───────┘
(5 rows)
```

**Comment by whit537** [comment]
```
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
│ 2012-06-22 │  25.29 │  4.62 │
```

**Comment by whit537** [comment]
```
│ 2012-06-22 │  25.29 │  4.62 │
```

That's our first week on Stripe as represented in the database, and it matches with our records in Stripe and with New Alliance. Stripe's fee was $4.32 (we were charging 3.9% + 30¢ at the time), so we saw $20.97 in New Alliance. We will need to get Stripe in Xero properly in order to reconcile: https://github.com/gratipay/inside.gratipay.com/pull/390#issuecomment-155890609 (+ pending).

**Comment by whit537** [comment]
```
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
```

```
6/25/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/22/2012	EFT DEP - STRIPE MERCHANT				$0.22	$106.45	Samurai -> Stripe
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.01	$106.23	samurai by feefighters
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.92	$104.22	samurai by feefighters
6/11/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$24.11	$103.30	samurai by feefighters
6/11/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
```
6/22/2012   EFT DEP - STRIPE MERCHANT               $0.22   $106.45 Samurai -> Stripe
```

This was a test transaction manually initiated on 6/15 right after Samurai [fell over on us](http://blog.gittip.com/post/25565694263/how-not-to-get-acquired/). It does not touch the Gratipay database.

**Comment by whit537** [comment]
```
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
```

```
6/25/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.01	$106.23	samurai by feefighters
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.92	$104.22	samurai by feefighters
6/11/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$24.11	$103.30	samurai by feefighters
6/11/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
```
6/18/2012   EFT DEP - MERCHANT BANKCD DEPOSIT       $2.92   $104.22 samurai by feefighters
```

Based on patterns going back before 6/1, this is for IHasAMoney.com

**Comment by whit537** [comment]
```
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
```

```
6/25/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$2.99	$109.44	samurai by feefighters
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.01	$106.23	samurai by feefighters
6/11/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$24.11	$103.30	samurai by feefighters
6/11/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
```
6/25/2012   EFT DEP - AMERICAN EXPRESS SETTLEMENT   $2.99   $109.44 samurai by feefighters
```

We're calling this another IHasAMoney.com fee. It looks like VISA/Mastercard transactions resulted in deposits of 2.92 to our bank account, and variable interchange fees in the vicinity of 8¢. We're also seeing some 5.84 charges with interchange fees like 11¢ or 13¢. Who the heck knows. Samurai charged us $163.82 out of the blue a month later, which is way more than we ever moved with them. Blech.

**Comment by whit537** [comment]
```
│ 2012-06-01 │   3.30 │  0.34 │
│ 2012-06-08 │  25.28 │  2.11 │
│ 2012-06-15 │   2.05 │  0.69 │
```

```
6/18/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$2.01	$106.23	samurai by feefighters
6/11/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$24.11	$103.30	samurai by feefighters
6/11/2012	EFT DEP - AMERICAN EXPRESS SETTLEMENT	$0.61	$79.19	samurai by feefighters
6/4/2012	EFT DEP - MERCHANT BANKCD DEPOSIT		$7.56	$110.01	samurai by feefighters
```

**Comment by whit537** [comment]
The bottom line here is that we don't have a record from Samurai to reconcile against. We can't see what Samurai thinks we charged people and what they gave us. We only have our database (what *we* think we charged people) and the New Alliance statement (what we actually got from Samurai).

**Comment by whit537** [comment]
I just reviewed my private emails about IHasAMoney.com. The first mention I find is in February, 2012. PyCon was in March that year. Looks like IHAM shuttered in June and the domain expired in early April of 2013. The important point for this ticket is this bit from a message I sent when it closed:

> Hey man, how's it going? We met at PyCon and you signed up for IHazAMoney.com [*sic*]! Can I say thank you? Thank you. It really meant a lot to me that you were willing to do that. Unfortunately you were the only one. Okay, there was another guy, but he left after a month. There was also another guy, but he's a friend and I made him sign up. I also signed up, but that doesn't count.

I'm almost positive that I charged $2.99 for it.

**Comment by whit537** [comment]
I also found an email I sent to five people who signed up for IHAM, and a second email to a sixth person.

**Comment by whit537** [comment]
Here are the New Alliance deposits I see (going back through 2012-01) that look to me like IHAM:

```
2012-03-02  5.84
2012-03-19  2.92
2012-03-26  2.92
2012-04-04  5.84
2012-04-18  2.92
2012-05-01  5.84
2012-05-18  2.92
2012-05-31  5.84
2012-06-18  2.92
2012-06-25  2.99
2012-07-02  2.92
```

**Comment by whit537** [comment]
I think the take-aways re: IHAM for this ticket are:

 - The 7.56 on June 4 does not include any IHAM money. On the one hand, we have a clear case, on June 18, where we received IHAM and non-IHAM funds in separate deposits. On the other, the 5.84 towards the beginning of the month appears to have hit early for June, on May 31.
 - The 2.99 on June 25 is best interpreted as an IHAM charge. We have a clear AMEX charge on June 11 for 0.61, and it hits the same day as non-AMEX charges clearly from June 8's payday. Besides, we were no longer running Gittip on Samurai by June 25 at all (June 15 was the last payday on Samurai). I'm almost positive, based on personal recollection, that the cost for IHAM was 2.99. I haven't been able to find source code for IHAM to verify this. There are a couple more places I could dig, but I'm pretty positive. I think it's best to interepret the 2.92 (and 5.84 = 2  * 2.92) vs. 2.99 as a difference between fee structures for non-AMEX and AMEX cards via Samurai.

Therefore we have three IHAM charges within scope for setting up Gratipay's books (our conversion date is June 1, 2012).

**Comment by whit537** [comment]
Now, what the heck to do with the remaining Samurai deposits ...

**Comment by whit537** [comment]
... which doooooo nnoooottttttt line up with the bank deposits we saw:

| payday date | amount charged ($) | deposit date | amount deposited ($) |
|---|-------|--------|---------|
| 2012-06-01 | 3.30 | 2012-06-04 | 7.56 |
| 2012-06-08 | 25.28 | 2012-06-11 | 24.72 |
| 2012-06-15 | 2.05 | 2012-06-18 | 2.01 |

**Comment by whit537** [comment]
Alright, welllllllllll .......................................

**Comment by whit537** [comment]
Since we don't have a Samurai statement to reconcile with, we have to either pick the database as the canonical record or the New Alliance statement. If we decide that the New Alliance statement is correct, then we have to rewrite exchange and possibly transfer history in the database. Let's inspect the database for errors, but baring any, we are left with the db as canonical, and an assumption of error on Samurai's part—not unlikely, given their untrustworthiness.

If we don't find an error in the database, I propose that we account for the Samurai discrepancy of $3.66 with a transfer from `Escrow - New Alliance` to `New Alliance`—a special-case transfer between escrow and operations, in view of the severe untrustworthiness of Samurai, the lack of good information at this late date, and the small amount of the funds in question.

**Comment by whit537** [comment]
This would be dated sometime in June, 2012 so that it's reflected in the reports for that month.

**Comment by whit537** [comment]
What we're saying is that, to the best of our knowledge and reconstruction, Samurai made an error and sent us net $3.66 more than they should've. We're accounting for this error as miscellaneous income to Gratipay.

**Comment by whit537** [comment]
"Here, hold this $10 on behalf of my friend."

Looking three years later, we see that it's a $20 bill the handed us.

**Comment by whit537** [comment]
Let's ensure that the $3.66 ends up in the processing fee fund: a special fund kept separate from the rest of operations, to handle the inevitable variance in our efforts to charge as little as possible in hard payment processing fees.

**Comment by kaguillera** [comment]
+1 to creating a separate account to handle variances.

**Comment by whit537** [comment]
What are the accounts to reconcile for the month of June, 2012? New Alliance, Samurai, Stripe, and Gratipay.

**Comment by whit537** [comment]
And cash. We paid out Steve in June, 2012.

**Comment by whit537** [comment]
We're talking about storing downloaded bank statements in the `logs` repo. We already have this to an extent but it's messy. We're talking about how we want to organize those.

 - operations, escrow
 - year, month
 - PDF, CSV
 - institution (banks, processors)

**Comment by whit537** [comment]
Here's what we're coming up with. The top-level is file format(!) because the two file formats serve fundamentally different purposes: CSVs will be used in our month-end reconciliation process, while PDFs will be used less often for manual checks and general record-keeping.

Different institutions provide different PDF formats and month offsets (Citizens on the 10th of the month, Ally on the 1st, etc.) and also combine or don't combine different accounts in various ways. Rather than trying to fold all those together, we can handle the variance by making institution the top level under `pdf`, with year and month below that.

For CSV, we are going to be sitting down to do month-end reconciliation, and we want to be in a single directory and compile all of the statements across all institutions. We'll be able to control the date ranges, and we'll get various raw formats that we'll transform into the CSV form we want in order to upload to Xero.

```
csv
  2012
    06
      raw
        escrow-new-alliance.csv
      escrow-new-alliance.csv
pdf
  ally
    2014
      06.pdf
  citizens
  pnc
    
```

**Comment by whit537** [comment]
Moving over to a PR in the new finances repo: https://github.com/gratipay/finances/pull/1.

**Comment by whit537** [comment]
Closing in favor of https://github.com/gratipay/finances/pull/1.
