### ISSUE TITLE
rename Gittip to ... Gratipay!

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/inside.gratipay.com#73]
It's time. See https://github.com/gittip/www.gittip.com/issues/138 for our first go-round on renaming, nearly two years ago.
#### Task List

Internal:
- [x] Freenode
- [x] BotBot
- [x] ~~Slack~~ Not going to worry about this one, since it's moribund.
- [x] building.gittip.com
- [x] GitHub
- [x] Medium
- [x] roobot
- [x] gittip-access-dashboard

Customer Support:
- [x] Google Apps
- [x] Freshdesk

Marketing:
- [x] Twitter
- [x] Facebook
- [x] Google+
- [x] Tumblr
- [x] open graph entries (Facebook, Twitter)

Hosting &amp; Product:
- [x] Heroku
- [x] Digital Ocean
- [x] MaxCDN
- [x] Typography.com
- [x] UptimeRobot
- [x] Pagerduty
- [x] Sentry
- [x] SSL certificate
- [x] Twitter OAuth app
- [x] GitHub OAuth app
- [x] Bitbucket OAuth app
- [x] Bountysource OAuth app
- [x] OpenStreetMap OAuth app
- [x] Venmo OAuth app
- [x] www.gittip.com
- [x] gttp.co
- [x] Gittip-Everywhere

Legal:
- [x] LLC

Financial:
- [x] Gratipay
- [x] Balanced
- [x] PayPal
- [x] Coinbase
- [x] Ally
- [x] New Alliance

Afterwards:
- [x] Update Vagrant box
- [x] Update username/email with all vendors
- [x] Update LLC name in legalese
- [x] [Check links](http://www.brokenlinkcheck.com/) in all places that we have control over.
#### Rationale

`Gittip` has been a serviceable name for the past two years, but it's not ideal. For most people, `Gittip` doesn't have any relevant natural associations; it doesn't suggest anything about [our mission](http://building.gittip.com/big-picture/mission). It's hard to spell, hard to pronounce, and hard to remember. For people who know what git and GitHub are the situation is worse, because `Gittip` puts us in a box we don't want to be in. We're building a mass-market product, not something for a tech niche. And for pete's sake, my _own kids_ [confuse Gittip with GitHub](https://github.com/gittip/www.gittip.com/issues/539#issuecomment-34827162).

Benefits of `Gratipay`:
- `Gratitude` + `pay` strongly suggests themes directly related to [our mission](http://building.gittip.com/big-picture/mission).
- The other association (I think it's maybe going to be stronger for Europeans?) is `gratis` (as in "free") + `pay`. We can live with that, right?
- It's pretty unambiguous to spell and pronounce.
- It's not actually that different from `Gittip` (the Levenshtein distance is 4 :-) ).
- It actually has the word `tip` tucked in there (assuming we still want to use that word).
- We can keep the heart coin logo.
- I was able to secure `gratipay` in the com, net, org, and co TLDs, as well as on Twitter, Facebook, Google+, GitHub, and Freenode. :scream_cat:

Drawbacks of `Gratipay`:
- Yes, eight letters + three syllables is the upper limit for a strong name. At least the syllables are short. `Amazon` and `Microsoft` are both doing okay. `Patreon`, too. :-)
- If the primary association is `gratis` + `pay` that's not totally ideal, but it still _kinda_ fits our mission, and at least `gratitude` + `pay` is present as a secondary association.

If you have a really compelling reason to _veto_ `Gratipay`, please share it ("In {Chinese,Arabic,Russian} that word is a heinous insult!"). Otherwise, let it sink in. We've been building Gittip for two years. Now let's build Gratipay! :D

![screen shot 2014-07-01 at 12 22 50 pm](https://cloud.githubusercontent.com/assets/134455/3445997/9c4c9f72-013c-11e4-937d-c616fac74cd9.png)
