### ISSUE TITLE
Cooperate!

### ISSUE THREAD

**Issue by whit537** [gratipay/inside.gratipay.com#995]
-------------------------------

✈️  **This is the flight deck for the [Cooperate!](https://github.com/orgs/gratipay/projects/17?fullscreen=true) project.** ✈️ 

-------------------------------

The goal of this project is to convert Gratipay into a [worker-owned cooperative](http://community-wealth.org/content/worker-cooperatives). The definition of "done" is that https://inside.gratipay.com/ is migrated to https://gratipay.coop/ with a blog post announcement. Tentative target date is June 1, 2017, our fifth birthday.

### Todo

- [x] adopt cooperative principles: https://github.com/gratipay/inside.gratipay.com/issues/995
- [x] bring on a second owner: https://github.com/gratipay/inside.gratipay.com/issues/196
- [ ] ...
- [ ] procure and migrate to gratipay.coop: https://github.com/gratipay/inside.gratipay.com/issues/996
